// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ad_content_entry.proto

package com.umeng.ufp.core.domain.protobuf;

public final class AdContentProtos {
  private AdContentProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public static final class AdContentEntry extends
      com.google.protobuf.GeneratedMessage {
    // Use AdContentEntry.newBuilder() to construct.
    private AdContentEntry() {
      initFields();
    }
    private AdContentEntry(boolean noInit) {}
    
    private static final AdContentEntry defaultInstance;
    public static AdContentEntry getDefaultInstance() {
      return defaultInstance;
    }
    
    public AdContentEntry getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.umeng.ufp.core.domain.protobuf.AdContentProtos.internal_static_com_umeng_ufp_core_domain_protobuf_AdContentEntry_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.umeng.ufp.core.domain.protobuf.AdContentProtos.internal_static_com_umeng_ufp_core_domain_protobuf_AdContentEntry_fieldAccessorTable;
    }
    
    // optional int32 id = 1;
    public static final int ID_FIELD_NUMBER = 1;
    private boolean hasId;
    private int id_ = 0;
    public boolean hasId() { return hasId; }
    public int getId() { return id_; }
    
    // optional string entry_type = 2;
    public static final int ENTRY_TYPE_FIELD_NUMBER = 2;
    private boolean hasEntryType;
    private java.lang.String entryType_ = "";
    public boolean hasEntryType() { return hasEntryType; }
    public java.lang.String getEntryType() { return entryType_; }
    
    // optional string content_type = 3;
    public static final int CONTENT_TYPE_FIELD_NUMBER = 3;
    private boolean hasContentType;
    private java.lang.String contentType_ = "";
    public boolean hasContentType() { return hasContentType; }
    public java.lang.String getContentType() { return contentType_; }
    
    // optional string display_type = 4;
    public static final int DISPLAY_TYPE_FIELD_NUMBER = 4;
    private boolean hasDisplayType;
    private java.lang.String displayType_ = "";
    public boolean hasDisplayType() { return hasDisplayType; }
    public java.lang.String getDisplayType() { return displayType_; }
    
    // optional string landing_type = 5;
    public static final int LANDING_TYPE_FIELD_NUMBER = 5;
    private boolean hasLandingType;
    private java.lang.String landingType_ = "";
    public boolean hasLandingType() { return hasLandingType; }
    public java.lang.String getLandingType() { return landingType_; }
    
    // optional string landing_size = 6;
    public static final int LANDING_SIZE_FIELD_NUMBER = 6;
    private boolean hasLandingSize;
    private java.lang.String landingSize_ = "";
    public boolean hasLandingSize() { return hasLandingSize; }
    public java.lang.String getLandingSize() { return landingSize_; }
    
    // optional string url = 7;
    public static final int URL_FIELD_NUMBER = 7;
    private boolean hasUrl;
    private java.lang.String url_ = "";
    public boolean hasUrl() { return hasUrl; }
    public java.lang.String getUrl() { return url_; }
    
    // optional string icon = 8;
    public static final int ICON_FIELD_NUMBER = 8;
    private boolean hasIcon;
    private java.lang.String icon_ = "";
    public boolean hasIcon() { return hasIcon; }
    public java.lang.String getIcon() { return icon_; }
    
    // optional string img = 9;
    public static final int IMG_FIELD_NUMBER = 9;
    private boolean hasImg;
    private java.lang.String img_ = "";
    public boolean hasImg() { return hasImg; }
    public java.lang.String getImg() { return img_; }
    
    // optional string title = 10;
    public static final int TITLE_FIELD_NUMBER = 10;
    private boolean hasTitle;
    private java.lang.String title_ = "";
    public boolean hasTitle() { return hasTitle; }
    public java.lang.String getTitle() { return title_; }
    
    // optional string text_font = 11;
    public static final int TEXT_FONT_FIELD_NUMBER = 11;
    private boolean hasTextFont;
    private java.lang.String textFont_ = "";
    public boolean hasTextFont() { return hasTextFont; }
    public java.lang.String getTextFont() { return textFont_; }
    
    // optional string text_color = 12;
    public static final int TEXT_COLOR_FIELD_NUMBER = 12;
    private boolean hasTextColor;
    private java.lang.String textColor_ = "";
    public boolean hasTextColor() { return hasTextColor; }
    public java.lang.String getTextColor() { return textColor_; }
    
    // optional string text_size = 13;
    public static final int TEXT_SIZE_FIELD_NUMBER = 13;
    private boolean hasTextSize;
    private java.lang.String textSize_ = "";
    public boolean hasTextSize() { return hasTextSize; }
    public java.lang.String getTextSize() { return textSize_; }
    
    // optional string ad_words = 14;
    public static final int AD_WORDS_FIELD_NUMBER = 14;
    private boolean hasAdWords;
    private java.lang.String adWords_ = "";
    public boolean hasAdWords() { return hasAdWords; }
    public java.lang.String getAdWords() { return adWords_; }
    
    // optional string provider = 15;
    public static final int PROVIDER_FIELD_NUMBER = 15;
    private boolean hasProvider;
    private java.lang.String provider_ = "";
    public boolean hasProvider() { return hasProvider; }
    public java.lang.String getProvider() { return provider_; }
    
    // optional string description = 16;
    public static final int DESCRIPTION_FIELD_NUMBER = 16;
    private boolean hasDescription;
    private java.lang.String description_ = "";
    public boolean hasDescription() { return hasDescription; }
    public java.lang.String getDescription() { return description_; }
    
    // optional string price = 17;
    public static final int PRICE_FIELD_NUMBER = 17;
    private boolean hasPrice;
    private java.lang.String price_ = "";
    public boolean hasPrice() { return hasPrice; }
    public java.lang.String getPrice() { return price_; }
    
    // optional string platform = 18;
    public static final int PLATFORM_FIELD_NUMBER = 18;
    private boolean hasPlatform;
    private java.lang.String platform_ = "";
    public boolean hasPlatform() { return hasPlatform; }
    public java.lang.String getPlatform() { return platform_; }
    
    // optional string template = 19;
    public static final int TEMPLATE_FIELD_NUMBER = 19;
    private boolean hasTemplate;
    private java.lang.String template_ = "";
    public boolean hasTemplate() { return hasTemplate; }
    public java.lang.String getTemplate() { return template_; }
    
    // optional int32 size = 20;
    public static final int SIZE_FIELD_NUMBER = 20;
    private boolean hasSize;
    private int size_ = 0;
    public boolean hasSize() { return hasSize; }
    public int getSize() { return size_; }
    
    // optional string app_package_name = 21;
    public static final int APP_PACKAGE_NAME_FIELD_NUMBER = 21;
    private boolean hasAppPackageName;
    private java.lang.String appPackageName_ = "";
    public boolean hasAppPackageName() { return hasAppPackageName; }
    public java.lang.String getAppPackageName() { return appPackageName_; }
    
    // optional string app_version_code = 22;
    public static final int APP_VERSION_CODE_FIELD_NUMBER = 22;
    private boolean hasAppVersionCode;
    private java.lang.String appVersionCode_ = "";
    public boolean hasAppVersionCode() { return hasAppVersionCode; }
    public java.lang.String getAppVersionCode() { return appVersionCode_; }
    
    // optional string app_version_name = 23;
    public static final int APP_VERSION_NAME_FIELD_NUMBER = 23;
    private boolean hasAppVersionName;
    private java.lang.String appVersionName_ = "";
    public boolean hasAppVersionName() { return hasAppVersionName; }
    public java.lang.String getAppVersionName() { return appVersionName_; }
    
    // optional string app_store_id = 24;
    public static final int APP_STORE_ID_FIELD_NUMBER = 24;
    private boolean hasAppStoreId;
    private java.lang.String appStoreId_ = "";
    public boolean hasAppStoreId() { return hasAppStoreId; }
    public java.lang.String getAppStoreId() { return appStoreId_; }
    
    // optional string bundle_identifier = 25;
    public static final int BUNDLE_IDENTIFIER_FIELD_NUMBER = 25;
    private boolean hasBundleIdentifier;
    private java.lang.String bundleIdentifier_ = "";
    public boolean hasBundleIdentifier() { return hasBundleIdentifier; }
    public java.lang.String getBundleIdentifier() { return bundleIdentifier_; }
    
    private void initFields() {
    }
    public final boolean isInitialized() {
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasId()) {
        output.writeInt32(1, getId());
      }
      if (hasEntryType()) {
        output.writeString(2, getEntryType());
      }
      if (hasContentType()) {
        output.writeString(3, getContentType());
      }
      if (hasDisplayType()) {
        output.writeString(4, getDisplayType());
      }
      if (hasLandingType()) {
        output.writeString(5, getLandingType());
      }
      if (hasLandingSize()) {
        output.writeString(6, getLandingSize());
      }
      if (hasUrl()) {
        output.writeString(7, getUrl());
      }
      if (hasIcon()) {
        output.writeString(8, getIcon());
      }
      if (hasImg()) {
        output.writeString(9, getImg());
      }
      if (hasTitle()) {
        output.writeString(10, getTitle());
      }
      if (hasTextFont()) {
        output.writeString(11, getTextFont());
      }
      if (hasTextColor()) {
        output.writeString(12, getTextColor());
      }
      if (hasTextSize()) {
        output.writeString(13, getTextSize());
      }
      if (hasAdWords()) {
        output.writeString(14, getAdWords());
      }
      if (hasProvider()) {
        output.writeString(15, getProvider());
      }
      if (hasDescription()) {
        output.writeString(16, getDescription());
      }
      if (hasPrice()) {
        output.writeString(17, getPrice());
      }
      if (hasPlatform()) {
        output.writeString(18, getPlatform());
      }
      if (hasTemplate()) {
        output.writeString(19, getTemplate());
      }
      if (hasSize()) {
        output.writeInt32(20, getSize());
      }
      if (hasAppPackageName()) {
        output.writeString(21, getAppPackageName());
      }
      if (hasAppVersionCode()) {
        output.writeString(22, getAppVersionCode());
      }
      if (hasAppVersionName()) {
        output.writeString(23, getAppVersionName());
      }
      if (hasAppStoreId()) {
        output.writeString(24, getAppStoreId());
      }
      if (hasBundleIdentifier()) {
        output.writeString(25, getBundleIdentifier());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasId()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, getId());
      }
      if (hasEntryType()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(2, getEntryType());
      }
      if (hasContentType()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(3, getContentType());
      }
      if (hasDisplayType()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(4, getDisplayType());
      }
      if (hasLandingType()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(5, getLandingType());
      }
      if (hasLandingSize()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(6, getLandingSize());
      }
      if (hasUrl()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(7, getUrl());
      }
      if (hasIcon()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(8, getIcon());
      }
      if (hasImg()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(9, getImg());
      }
      if (hasTitle()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(10, getTitle());
      }
      if (hasTextFont()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(11, getTextFont());
      }
      if (hasTextColor()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(12, getTextColor());
      }
      if (hasTextSize()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(13, getTextSize());
      }
      if (hasAdWords()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(14, getAdWords());
      }
      if (hasProvider()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(15, getProvider());
      }
      if (hasDescription()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(16, getDescription());
      }
      if (hasPrice()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(17, getPrice());
      }
      if (hasPlatform()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(18, getPlatform());
      }
      if (hasTemplate()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(19, getTemplate());
      }
      if (hasSize()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(20, getSize());
      }
      if (hasAppPackageName()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(21, getAppPackageName());
      }
      if (hasAppVersionCode()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(22, getAppVersionCode());
      }
      if (hasAppVersionName()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(23, getAppVersionName());
      }
      if (hasAppStoreId()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(24, getAppStoreId());
      }
      if (hasBundleIdentifier()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(25, getBundleIdentifier());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static com.umeng.ufp.core.domain.protobuf.AdContentProtos.AdContentEntry parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.umeng.ufp.core.domain.protobuf.AdContentProtos.AdContentEntry parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.umeng.ufp.core.domain.protobuf.AdContentProtos.AdContentEntry parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.umeng.ufp.core.domain.protobuf.AdContentProtos.AdContentEntry parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.umeng.ufp.core.domain.protobuf.AdContentProtos.AdContentEntry parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.umeng.ufp.core.domain.protobuf.AdContentProtos.AdContentEntry parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.umeng.ufp.core.domain.protobuf.AdContentProtos.AdContentEntry parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.umeng.ufp.core.domain.protobuf.AdContentProtos.AdContentEntry parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.umeng.ufp.core.domain.protobuf.AdContentProtos.AdContentEntry parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.umeng.ufp.core.domain.protobuf.AdContentProtos.AdContentEntry parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.umeng.ufp.core.domain.protobuf.AdContentProtos.AdContentEntry prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private com.umeng.ufp.core.domain.protobuf.AdContentProtos.AdContentEntry result;
      
      // Construct using com.umeng.ufp.core.domain.protobuf.AdContentProtos.AdContentEntry.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new com.umeng.ufp.core.domain.protobuf.AdContentProtos.AdContentEntry();
        return builder;
      }
      
      protected com.umeng.ufp.core.domain.protobuf.AdContentProtos.AdContentEntry internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new com.umeng.ufp.core.domain.protobuf.AdContentProtos.AdContentEntry();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.umeng.ufp.core.domain.protobuf.AdContentProtos.AdContentEntry.getDescriptor();
      }
      
      public com.umeng.ufp.core.domain.protobuf.AdContentProtos.AdContentEntry getDefaultInstanceForType() {
        return com.umeng.ufp.core.domain.protobuf.AdContentProtos.AdContentEntry.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public com.umeng.ufp.core.domain.protobuf.AdContentProtos.AdContentEntry build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private com.umeng.ufp.core.domain.protobuf.AdContentProtos.AdContentEntry buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.umeng.ufp.core.domain.protobuf.AdContentProtos.AdContentEntry buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        com.umeng.ufp.core.domain.protobuf.AdContentProtos.AdContentEntry returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.umeng.ufp.core.domain.protobuf.AdContentProtos.AdContentEntry) {
          return mergeFrom((com.umeng.ufp.core.domain.protobuf.AdContentProtos.AdContentEntry)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.umeng.ufp.core.domain.protobuf.AdContentProtos.AdContentEntry other) {
        if (other == com.umeng.ufp.core.domain.protobuf.AdContentProtos.AdContentEntry.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasEntryType()) {
          setEntryType(other.getEntryType());
        }
        if (other.hasContentType()) {
          setContentType(other.getContentType());
        }
        if (other.hasDisplayType()) {
          setDisplayType(other.getDisplayType());
        }
        if (other.hasLandingType()) {
          setLandingType(other.getLandingType());
        }
        if (other.hasLandingSize()) {
          setLandingSize(other.getLandingSize());
        }
        if (other.hasUrl()) {
          setUrl(other.getUrl());
        }
        if (other.hasIcon()) {
          setIcon(other.getIcon());
        }
        if (other.hasImg()) {
          setImg(other.getImg());
        }
        if (other.hasTitle()) {
          setTitle(other.getTitle());
        }
        if (other.hasTextFont()) {
          setTextFont(other.getTextFont());
        }
        if (other.hasTextColor()) {
          setTextColor(other.getTextColor());
        }
        if (other.hasTextSize()) {
          setTextSize(other.getTextSize());
        }
        if (other.hasAdWords()) {
          setAdWords(other.getAdWords());
        }
        if (other.hasProvider()) {
          setProvider(other.getProvider());
        }
        if (other.hasDescription()) {
          setDescription(other.getDescription());
        }
        if (other.hasPrice()) {
          setPrice(other.getPrice());
        }
        if (other.hasPlatform()) {
          setPlatform(other.getPlatform());
        }
        if (other.hasTemplate()) {
          setTemplate(other.getTemplate());
        }
        if (other.hasSize()) {
          setSize(other.getSize());
        }
        if (other.hasAppPackageName()) {
          setAppPackageName(other.getAppPackageName());
        }
        if (other.hasAppVersionCode()) {
          setAppVersionCode(other.getAppVersionCode());
        }
        if (other.hasAppVersionName()) {
          setAppVersionName(other.getAppVersionName());
        }
        if (other.hasAppStoreId()) {
          setAppStoreId(other.getAppStoreId());
        }
        if (other.hasBundleIdentifier()) {
          setBundleIdentifier(other.getBundleIdentifier());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 8: {
              setId(input.readInt32());
              break;
            }
            case 18: {
              setEntryType(input.readString());
              break;
            }
            case 26: {
              setContentType(input.readString());
              break;
            }
            case 34: {
              setDisplayType(input.readString());
              break;
            }
            case 42: {
              setLandingType(input.readString());
              break;
            }
            case 50: {
              setLandingSize(input.readString());
              break;
            }
            case 58: {
              setUrl(input.readString());
              break;
            }
            case 66: {
              setIcon(input.readString());
              break;
            }
            case 74: {
              setImg(input.readString());
              break;
            }
            case 82: {
              setTitle(input.readString());
              break;
            }
            case 90: {
              setTextFont(input.readString());
              break;
            }
            case 98: {
              setTextColor(input.readString());
              break;
            }
            case 106: {
              setTextSize(input.readString());
              break;
            }
            case 114: {
              setAdWords(input.readString());
              break;
            }
            case 122: {
              setProvider(input.readString());
              break;
            }
            case 130: {
              setDescription(input.readString());
              break;
            }
            case 138: {
              setPrice(input.readString());
              break;
            }
            case 146: {
              setPlatform(input.readString());
              break;
            }
            case 154: {
              setTemplate(input.readString());
              break;
            }
            case 160: {
              setSize(input.readInt32());
              break;
            }
            case 170: {
              setAppPackageName(input.readString());
              break;
            }
            case 178: {
              setAppVersionCode(input.readString());
              break;
            }
            case 186: {
              setAppVersionName(input.readString());
              break;
            }
            case 194: {
              setAppStoreId(input.readString());
              break;
            }
            case 202: {
              setBundleIdentifier(input.readString());
              break;
            }
          }
        }
      }
      
      
      // optional int32 id = 1;
      public boolean hasId() {
        return result.hasId();
      }
      public int getId() {
        return result.getId();
      }
      public Builder setId(int value) {
        result.hasId = true;
        result.id_ = value;
        return this;
      }
      public Builder clearId() {
        result.hasId = false;
        result.id_ = 0;
        return this;
      }
      
      // optional string entry_type = 2;
      public boolean hasEntryType() {
        return result.hasEntryType();
      }
      public java.lang.String getEntryType() {
        return result.getEntryType();
      }
      public Builder setEntryType(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasEntryType = true;
        result.entryType_ = value;
        return this;
      }
      public Builder clearEntryType() {
        result.hasEntryType = false;
        result.entryType_ = getDefaultInstance().getEntryType();
        return this;
      }
      
      // optional string content_type = 3;
      public boolean hasContentType() {
        return result.hasContentType();
      }
      public java.lang.String getContentType() {
        return result.getContentType();
      }
      public Builder setContentType(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasContentType = true;
        result.contentType_ = value;
        return this;
      }
      public Builder clearContentType() {
        result.hasContentType = false;
        result.contentType_ = getDefaultInstance().getContentType();
        return this;
      }
      
      // optional string display_type = 4;
      public boolean hasDisplayType() {
        return result.hasDisplayType();
      }
      public java.lang.String getDisplayType() {
        return result.getDisplayType();
      }
      public Builder setDisplayType(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasDisplayType = true;
        result.displayType_ = value;
        return this;
      }
      public Builder clearDisplayType() {
        result.hasDisplayType = false;
        result.displayType_ = getDefaultInstance().getDisplayType();
        return this;
      }
      
      // optional string landing_type = 5;
      public boolean hasLandingType() {
        return result.hasLandingType();
      }
      public java.lang.String getLandingType() {
        return result.getLandingType();
      }
      public Builder setLandingType(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasLandingType = true;
        result.landingType_ = value;
        return this;
      }
      public Builder clearLandingType() {
        result.hasLandingType = false;
        result.landingType_ = getDefaultInstance().getLandingType();
        return this;
      }
      
      // optional string landing_size = 6;
      public boolean hasLandingSize() {
        return result.hasLandingSize();
      }
      public java.lang.String getLandingSize() {
        return result.getLandingSize();
      }
      public Builder setLandingSize(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasLandingSize = true;
        result.landingSize_ = value;
        return this;
      }
      public Builder clearLandingSize() {
        result.hasLandingSize = false;
        result.landingSize_ = getDefaultInstance().getLandingSize();
        return this;
      }
      
      // optional string url = 7;
      public boolean hasUrl() {
        return result.hasUrl();
      }
      public java.lang.String getUrl() {
        return result.getUrl();
      }
      public Builder setUrl(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasUrl = true;
        result.url_ = value;
        return this;
      }
      public Builder clearUrl() {
        result.hasUrl = false;
        result.url_ = getDefaultInstance().getUrl();
        return this;
      }
      
      // optional string icon = 8;
      public boolean hasIcon() {
        return result.hasIcon();
      }
      public java.lang.String getIcon() {
        return result.getIcon();
      }
      public Builder setIcon(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasIcon = true;
        result.icon_ = value;
        return this;
      }
      public Builder clearIcon() {
        result.hasIcon = false;
        result.icon_ = getDefaultInstance().getIcon();
        return this;
      }
      
      // optional string img = 9;
      public boolean hasImg() {
        return result.hasImg();
      }
      public java.lang.String getImg() {
        return result.getImg();
      }
      public Builder setImg(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasImg = true;
        result.img_ = value;
        return this;
      }
      public Builder clearImg() {
        result.hasImg = false;
        result.img_ = getDefaultInstance().getImg();
        return this;
      }
      
      // optional string title = 10;
      public boolean hasTitle() {
        return result.hasTitle();
      }
      public java.lang.String getTitle() {
        return result.getTitle();
      }
      public Builder setTitle(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasTitle = true;
        result.title_ = value;
        return this;
      }
      public Builder clearTitle() {
        result.hasTitle = false;
        result.title_ = getDefaultInstance().getTitle();
        return this;
      }
      
      // optional string text_font = 11;
      public boolean hasTextFont() {
        return result.hasTextFont();
      }
      public java.lang.String getTextFont() {
        return result.getTextFont();
      }
      public Builder setTextFont(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasTextFont = true;
        result.textFont_ = value;
        return this;
      }
      public Builder clearTextFont() {
        result.hasTextFont = false;
        result.textFont_ = getDefaultInstance().getTextFont();
        return this;
      }
      
      // optional string text_color = 12;
      public boolean hasTextColor() {
        return result.hasTextColor();
      }
      public java.lang.String getTextColor() {
        return result.getTextColor();
      }
      public Builder setTextColor(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasTextColor = true;
        result.textColor_ = value;
        return this;
      }
      public Builder clearTextColor() {
        result.hasTextColor = false;
        result.textColor_ = getDefaultInstance().getTextColor();
        return this;
      }
      
      // optional string text_size = 13;
      public boolean hasTextSize() {
        return result.hasTextSize();
      }
      public java.lang.String getTextSize() {
        return result.getTextSize();
      }
      public Builder setTextSize(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasTextSize = true;
        result.textSize_ = value;
        return this;
      }
      public Builder clearTextSize() {
        result.hasTextSize = false;
        result.textSize_ = getDefaultInstance().getTextSize();
        return this;
      }
      
      // optional string ad_words = 14;
      public boolean hasAdWords() {
        return result.hasAdWords();
      }
      public java.lang.String getAdWords() {
        return result.getAdWords();
      }
      public Builder setAdWords(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasAdWords = true;
        result.adWords_ = value;
        return this;
      }
      public Builder clearAdWords() {
        result.hasAdWords = false;
        result.adWords_ = getDefaultInstance().getAdWords();
        return this;
      }
      
      // optional string provider = 15;
      public boolean hasProvider() {
        return result.hasProvider();
      }
      public java.lang.String getProvider() {
        return result.getProvider();
      }
      public Builder setProvider(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasProvider = true;
        result.provider_ = value;
        return this;
      }
      public Builder clearProvider() {
        result.hasProvider = false;
        result.provider_ = getDefaultInstance().getProvider();
        return this;
      }
      
      // optional string description = 16;
      public boolean hasDescription() {
        return result.hasDescription();
      }
      public java.lang.String getDescription() {
        return result.getDescription();
      }
      public Builder setDescription(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasDescription = true;
        result.description_ = value;
        return this;
      }
      public Builder clearDescription() {
        result.hasDescription = false;
        result.description_ = getDefaultInstance().getDescription();
        return this;
      }
      
      // optional string price = 17;
      public boolean hasPrice() {
        return result.hasPrice();
      }
      public java.lang.String getPrice() {
        return result.getPrice();
      }
      public Builder setPrice(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasPrice = true;
        result.price_ = value;
        return this;
      }
      public Builder clearPrice() {
        result.hasPrice = false;
        result.price_ = getDefaultInstance().getPrice();
        return this;
      }
      
      // optional string platform = 18;
      public boolean hasPlatform() {
        return result.hasPlatform();
      }
      public java.lang.String getPlatform() {
        return result.getPlatform();
      }
      public Builder setPlatform(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasPlatform = true;
        result.platform_ = value;
        return this;
      }
      public Builder clearPlatform() {
        result.hasPlatform = false;
        result.platform_ = getDefaultInstance().getPlatform();
        return this;
      }
      
      // optional string template = 19;
      public boolean hasTemplate() {
        return result.hasTemplate();
      }
      public java.lang.String getTemplate() {
        return result.getTemplate();
      }
      public Builder setTemplate(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasTemplate = true;
        result.template_ = value;
        return this;
      }
      public Builder clearTemplate() {
        result.hasTemplate = false;
        result.template_ = getDefaultInstance().getTemplate();
        return this;
      }
      
      // optional int32 size = 20;
      public boolean hasSize() {
        return result.hasSize();
      }
      public int getSize() {
        return result.getSize();
      }
      public Builder setSize(int value) {
        result.hasSize = true;
        result.size_ = value;
        return this;
      }
      public Builder clearSize() {
        result.hasSize = false;
        result.size_ = 0;
        return this;
      }
      
      // optional string app_package_name = 21;
      public boolean hasAppPackageName() {
        return result.hasAppPackageName();
      }
      public java.lang.String getAppPackageName() {
        return result.getAppPackageName();
      }
      public Builder setAppPackageName(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasAppPackageName = true;
        result.appPackageName_ = value;
        return this;
      }
      public Builder clearAppPackageName() {
        result.hasAppPackageName = false;
        result.appPackageName_ = getDefaultInstance().getAppPackageName();
        return this;
      }
      
      // optional string app_version_code = 22;
      public boolean hasAppVersionCode() {
        return result.hasAppVersionCode();
      }
      public java.lang.String getAppVersionCode() {
        return result.getAppVersionCode();
      }
      public Builder setAppVersionCode(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasAppVersionCode = true;
        result.appVersionCode_ = value;
        return this;
      }
      public Builder clearAppVersionCode() {
        result.hasAppVersionCode = false;
        result.appVersionCode_ = getDefaultInstance().getAppVersionCode();
        return this;
      }
      
      // optional string app_version_name = 23;
      public boolean hasAppVersionName() {
        return result.hasAppVersionName();
      }
      public java.lang.String getAppVersionName() {
        return result.getAppVersionName();
      }
      public Builder setAppVersionName(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasAppVersionName = true;
        result.appVersionName_ = value;
        return this;
      }
      public Builder clearAppVersionName() {
        result.hasAppVersionName = false;
        result.appVersionName_ = getDefaultInstance().getAppVersionName();
        return this;
      }
      
      // optional string app_store_id = 24;
      public boolean hasAppStoreId() {
        return result.hasAppStoreId();
      }
      public java.lang.String getAppStoreId() {
        return result.getAppStoreId();
      }
      public Builder setAppStoreId(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasAppStoreId = true;
        result.appStoreId_ = value;
        return this;
      }
      public Builder clearAppStoreId() {
        result.hasAppStoreId = false;
        result.appStoreId_ = getDefaultInstance().getAppStoreId();
        return this;
      }
      
      // optional string bundle_identifier = 25;
      public boolean hasBundleIdentifier() {
        return result.hasBundleIdentifier();
      }
      public java.lang.String getBundleIdentifier() {
        return result.getBundleIdentifier();
      }
      public Builder setBundleIdentifier(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasBundleIdentifier = true;
        result.bundleIdentifier_ = value;
        return this;
      }
      public Builder clearBundleIdentifier() {
        result.hasBundleIdentifier = false;
        result.bundleIdentifier_ = getDefaultInstance().getBundleIdentifier();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:com.umeng.ufp.core.domain.protobuf.AdContentEntry)
    }
    
    static {
      defaultInstance = new AdContentEntry(true);
      com.umeng.ufp.core.domain.protobuf.AdContentProtos.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.umeng.ufp.core.domain.protobuf.AdContentEntry)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_umeng_ufp_core_domain_protobuf_AdContentEntry_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_umeng_ufp_core_domain_protobuf_AdContentEntry_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\026ad_content_entry.proto\022\"com.umeng.ufp." +
      "core.domain.protobuf\"\362\003\n\016AdContentEntry\022" +
      "\n\n\002id\030\001 \001(\005\022\022\n\nentry_type\030\002 \001(\t\022\024\n\014conte" +
      "nt_type\030\003 \001(\t\022\024\n\014display_type\030\004 \001(\t\022\024\n\014l" +
      "anding_type\030\005 \001(\t\022\024\n\014landing_size\030\006 \001(\t\022" +
      "\013\n\003url\030\007 \001(\t\022\014\n\004icon\030\010 \001(\t\022\013\n\003img\030\t \001(\t\022" +
      "\r\n\005title\030\n \001(\t\022\021\n\ttext_font\030\013 \001(\t\022\022\n\ntex" +
      "t_color\030\014 \001(\t\022\021\n\ttext_size\030\r \001(\t\022\020\n\010ad_w" +
      "ords\030\016 \001(\t\022\020\n\010provider\030\017 \001(\t\022\023\n\013descript" +
      "ion\030\020 \001(\t\022\r\n\005price\030\021 \001(\t\022\020\n\010platform\030\022 \001",
      "(\t\022\020\n\010template\030\023 \001(\t\022\014\n\004size\030\024 \001(\005\022\030\n\020ap" +
      "p_package_name\030\025 \001(\t\022\030\n\020app_version_code" +
      "\030\026 \001(\t\022\030\n\020app_version_name\030\027 \001(\t\022\024\n\014app_" +
      "store_id\030\030 \001(\t\022\031\n\021bundle_identifier\030\031 \001(" +
      "\tB5\n\"com.umeng.ufp.core.domain.protobufB" +
      "\017AdContentProtos"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_umeng_ufp_core_domain_protobuf_AdContentEntry_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_umeng_ufp_core_domain_protobuf_AdContentEntry_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_umeng_ufp_core_domain_protobuf_AdContentEntry_descriptor,
              new java.lang.String[] { "Id", "EntryType", "ContentType", "DisplayType", "LandingType", "LandingSize", "Url", "Icon", "Img", "Title", "TextFont", "TextColor", "TextSize", "AdWords", "Provider", "Description", "Price", "Platform", "Template", "Size", "AppPackageName", "AppVersionCode", "AppVersionName", "AppStoreId", "BundleIdentifier", },
              com.umeng.ufp.core.domain.protobuf.AdContentProtos.AdContentEntry.class,
              com.umeng.ufp.core.domain.protobuf.AdContentProtos.AdContentEntry.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  public static void internalForceInit() {}
  
  // @@protoc_insertion_point(outer_class_scope)
}
