// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ad_order_entry.proto

package com.umeng.ufp.core.domain.protobuf;

public final class AdOrderProtos {
  private AdOrderProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public static final class AdOrderEntry extends
      com.google.protobuf.GeneratedMessage {
    // Use AdOrderEntry.newBuilder() to construct.
    private AdOrderEntry() {
      initFields();
    }
    private AdOrderEntry(boolean noInit) {}
    
    private static final AdOrderEntry defaultInstance;
    public static AdOrderEntry getDefaultInstance() {
      return defaultInstance;
    }
    
    public AdOrderEntry getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.umeng.ufp.core.domain.protobuf.AdOrderProtos.internal_static_com_umeng_ufp_core_domain_protobuf_AdOrderEntry_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.umeng.ufp.core.domain.protobuf.AdOrderProtos.internal_static_com_umeng_ufp_core_domain_protobuf_AdOrderEntry_fieldAccessorTable;
    }
    
    // optional int32 id = 1;
    public static final int ID_FIELD_NUMBER = 1;
    private boolean hasId;
    private int id_ = 0;
    public boolean hasId() { return hasId; }
    public int getId() { return id_; }
    
    // optional string name = 2;
    public static final int NAME_FIELD_NUMBER = 2;
    private boolean hasName;
    private java.lang.String name_ = "";
    public boolean hasName() { return hasName; }
    public java.lang.String getName() { return name_; }
    
    // optional string comments = 3;
    public static final int COMMENTS_FIELD_NUMBER = 3;
    private boolean hasComments;
    private java.lang.String comments_ = "";
    public boolean hasComments() { return hasComments; }
    public java.lang.String getComments() { return comments_; }
    
    // optional string customer = 4;
    public static final int CUSTOMER_FIELD_NUMBER = 4;
    private boolean hasCustomer;
    private java.lang.String customer_ = "";
    public boolean hasCustomer() { return hasCustomer; }
    public java.lang.String getCustomer() { return customer_; }
    
    // optional int64 start_time = 5;
    public static final int START_TIME_FIELD_NUMBER = 5;
    private boolean hasStartTime;
    private long startTime_ = 0L;
    public boolean hasStartTime() { return hasStartTime; }
    public long getStartTime() { return startTime_; }
    
    // optional int64 end_time = 6;
    public static final int END_TIME_FIELD_NUMBER = 6;
    private boolean hasEndTime;
    private long endTime_ = 0L;
    public boolean hasEndTime() { return hasEndTime; }
    public long getEndTime() { return endTime_; }
    
    // optional string status = 7;
    public static final int STATUS_FIELD_NUMBER = 7;
    private boolean hasStatus;
    private java.lang.String status_ = "";
    public boolean hasStatus() { return hasStatus; }
    public java.lang.String getStatus() { return status_; }
    
    private void initFields() {
    }
    public final boolean isInitialized() {
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasId()) {
        output.writeInt32(1, getId());
      }
      if (hasName()) {
        output.writeString(2, getName());
      }
      if (hasComments()) {
        output.writeString(3, getComments());
      }
      if (hasCustomer()) {
        output.writeString(4, getCustomer());
      }
      if (hasStartTime()) {
        output.writeInt64(5, getStartTime());
      }
      if (hasEndTime()) {
        output.writeInt64(6, getEndTime());
      }
      if (hasStatus()) {
        output.writeString(7, getStatus());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasId()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, getId());
      }
      if (hasName()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(2, getName());
      }
      if (hasComments()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(3, getComments());
      }
      if (hasCustomer()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(4, getCustomer());
      }
      if (hasStartTime()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(5, getStartTime());
      }
      if (hasEndTime()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(6, getEndTime());
      }
      if (hasStatus()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(7, getStatus());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static com.umeng.ufp.core.domain.protobuf.AdOrderProtos.AdOrderEntry parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.umeng.ufp.core.domain.protobuf.AdOrderProtos.AdOrderEntry parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.umeng.ufp.core.domain.protobuf.AdOrderProtos.AdOrderEntry parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.umeng.ufp.core.domain.protobuf.AdOrderProtos.AdOrderEntry parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.umeng.ufp.core.domain.protobuf.AdOrderProtos.AdOrderEntry parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.umeng.ufp.core.domain.protobuf.AdOrderProtos.AdOrderEntry parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.umeng.ufp.core.domain.protobuf.AdOrderProtos.AdOrderEntry parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.umeng.ufp.core.domain.protobuf.AdOrderProtos.AdOrderEntry parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.umeng.ufp.core.domain.protobuf.AdOrderProtos.AdOrderEntry parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.umeng.ufp.core.domain.protobuf.AdOrderProtos.AdOrderEntry parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.umeng.ufp.core.domain.protobuf.AdOrderProtos.AdOrderEntry prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private com.umeng.ufp.core.domain.protobuf.AdOrderProtos.AdOrderEntry result;
      
      // Construct using com.umeng.ufp.core.domain.protobuf.AdOrderProtos.AdOrderEntry.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new com.umeng.ufp.core.domain.protobuf.AdOrderProtos.AdOrderEntry();
        return builder;
      }
      
      protected com.umeng.ufp.core.domain.protobuf.AdOrderProtos.AdOrderEntry internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new com.umeng.ufp.core.domain.protobuf.AdOrderProtos.AdOrderEntry();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.umeng.ufp.core.domain.protobuf.AdOrderProtos.AdOrderEntry.getDescriptor();
      }
      
      public com.umeng.ufp.core.domain.protobuf.AdOrderProtos.AdOrderEntry getDefaultInstanceForType() {
        return com.umeng.ufp.core.domain.protobuf.AdOrderProtos.AdOrderEntry.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public com.umeng.ufp.core.domain.protobuf.AdOrderProtos.AdOrderEntry build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private com.umeng.ufp.core.domain.protobuf.AdOrderProtos.AdOrderEntry buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.umeng.ufp.core.domain.protobuf.AdOrderProtos.AdOrderEntry buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        com.umeng.ufp.core.domain.protobuf.AdOrderProtos.AdOrderEntry returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.umeng.ufp.core.domain.protobuf.AdOrderProtos.AdOrderEntry) {
          return mergeFrom((com.umeng.ufp.core.domain.protobuf.AdOrderProtos.AdOrderEntry)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.umeng.ufp.core.domain.protobuf.AdOrderProtos.AdOrderEntry other) {
        if (other == com.umeng.ufp.core.domain.protobuf.AdOrderProtos.AdOrderEntry.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasName()) {
          setName(other.getName());
        }
        if (other.hasComments()) {
          setComments(other.getComments());
        }
        if (other.hasCustomer()) {
          setCustomer(other.getCustomer());
        }
        if (other.hasStartTime()) {
          setStartTime(other.getStartTime());
        }
        if (other.hasEndTime()) {
          setEndTime(other.getEndTime());
        }
        if (other.hasStatus()) {
          setStatus(other.getStatus());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 8: {
              setId(input.readInt32());
              break;
            }
            case 18: {
              setName(input.readString());
              break;
            }
            case 26: {
              setComments(input.readString());
              break;
            }
            case 34: {
              setCustomer(input.readString());
              break;
            }
            case 40: {
              setStartTime(input.readInt64());
              break;
            }
            case 48: {
              setEndTime(input.readInt64());
              break;
            }
            case 58: {
              setStatus(input.readString());
              break;
            }
          }
        }
      }
      
      
      // optional int32 id = 1;
      public boolean hasId() {
        return result.hasId();
      }
      public int getId() {
        return result.getId();
      }
      public Builder setId(int value) {
        result.hasId = true;
        result.id_ = value;
        return this;
      }
      public Builder clearId() {
        result.hasId = false;
        result.id_ = 0;
        return this;
      }
      
      // optional string name = 2;
      public boolean hasName() {
        return result.hasName();
      }
      public java.lang.String getName() {
        return result.getName();
      }
      public Builder setName(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasName = true;
        result.name_ = value;
        return this;
      }
      public Builder clearName() {
        result.hasName = false;
        result.name_ = getDefaultInstance().getName();
        return this;
      }
      
      // optional string comments = 3;
      public boolean hasComments() {
        return result.hasComments();
      }
      public java.lang.String getComments() {
        return result.getComments();
      }
      public Builder setComments(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasComments = true;
        result.comments_ = value;
        return this;
      }
      public Builder clearComments() {
        result.hasComments = false;
        result.comments_ = getDefaultInstance().getComments();
        return this;
      }
      
      // optional string customer = 4;
      public boolean hasCustomer() {
        return result.hasCustomer();
      }
      public java.lang.String getCustomer() {
        return result.getCustomer();
      }
      public Builder setCustomer(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasCustomer = true;
        result.customer_ = value;
        return this;
      }
      public Builder clearCustomer() {
        result.hasCustomer = false;
        result.customer_ = getDefaultInstance().getCustomer();
        return this;
      }
      
      // optional int64 start_time = 5;
      public boolean hasStartTime() {
        return result.hasStartTime();
      }
      public long getStartTime() {
        return result.getStartTime();
      }
      public Builder setStartTime(long value) {
        result.hasStartTime = true;
        result.startTime_ = value;
        return this;
      }
      public Builder clearStartTime() {
        result.hasStartTime = false;
        result.startTime_ = 0L;
        return this;
      }
      
      // optional int64 end_time = 6;
      public boolean hasEndTime() {
        return result.hasEndTime();
      }
      public long getEndTime() {
        return result.getEndTime();
      }
      public Builder setEndTime(long value) {
        result.hasEndTime = true;
        result.endTime_ = value;
        return this;
      }
      public Builder clearEndTime() {
        result.hasEndTime = false;
        result.endTime_ = 0L;
        return this;
      }
      
      // optional string status = 7;
      public boolean hasStatus() {
        return result.hasStatus();
      }
      public java.lang.String getStatus() {
        return result.getStatus();
      }
      public Builder setStatus(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasStatus = true;
        result.status_ = value;
        return this;
      }
      public Builder clearStatus() {
        result.hasStatus = false;
        result.status_ = getDefaultInstance().getStatus();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:com.umeng.ufp.core.domain.protobuf.AdOrderEntry)
    }
    
    static {
      defaultInstance = new AdOrderEntry(true);
      com.umeng.ufp.core.domain.protobuf.AdOrderProtos.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.umeng.ufp.core.domain.protobuf.AdOrderEntry)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_umeng_ufp_core_domain_protobuf_AdOrderEntry_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_umeng_ufp_core_domain_protobuf_AdOrderEntry_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024ad_order_entry.proto\022\"com.umeng.ufp.co" +
      "re.domain.protobuf\"\202\001\n\014AdOrderEntry\022\n\n\002i" +
      "d\030\001 \001(\005\022\014\n\004name\030\002 \001(\t\022\020\n\010comments\030\003 \001(\t\022" +
      "\020\n\010customer\030\004 \001(\t\022\022\n\nstart_time\030\005 \001(\003\022\020\n" +
      "\010end_time\030\006 \001(\003\022\016\n\006status\030\007 \001(\tB3\n\"com.u" +
      "meng.ufp.core.domain.protobufB\rAdOrderPr" +
      "otos"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_umeng_ufp_core_domain_protobuf_AdOrderEntry_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_umeng_ufp_core_domain_protobuf_AdOrderEntry_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_umeng_ufp_core_domain_protobuf_AdOrderEntry_descriptor,
              new java.lang.String[] { "Id", "Name", "Comments", "Customer", "StartTime", "EndTime", "Status", },
              com.umeng.ufp.core.domain.protobuf.AdOrderProtos.AdOrderEntry.class,
              com.umeng.ufp.core.domain.protobuf.AdOrderProtos.AdOrderEntry.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  public static void internalForceInit() {}
  
  // @@protoc_insertion_point(outer_class_scope)
}
