// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ad_entry.proto

package com.umeng.ufp.core.domain.protobuf;

public final class AdProtos {
  private AdProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public static final class AdEntry extends
      com.google.protobuf.GeneratedMessage {
    // Use AdEntry.newBuilder() to construct.
    private AdEntry() {
      initFields();
    }
    private AdEntry(boolean noInit) {}
    
    private static final AdEntry defaultInstance;
    public static AdEntry getDefaultInstance() {
      return defaultInstance;
    }
    
    public AdEntry getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.umeng.ufp.core.domain.protobuf.AdProtos.internal_static_com_umeng_ufp_core_domain_protobuf_AdEntry_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.umeng.ufp.core.domain.protobuf.AdProtos.internal_static_com_umeng_ufp_core_domain_protobuf_AdEntry_fieldAccessorTable;
    }
    
    // optional int32 id = 1;
    public static final int ID_FIELD_NUMBER = 1;
    private boolean hasId;
    private int id_ = 0;
    public boolean hasId() { return hasId; }
    public int getId() { return id_; }
    
    // optional int32 ad_order_id = 2;
    public static final int AD_ORDER_ID_FIELD_NUMBER = 2;
    private boolean hasAdOrderId;
    private int adOrderId_ = 0;
    public boolean hasAdOrderId() { return hasAdOrderId; }
    public int getAdOrderId() { return adOrderId_; }
    
    // optional string name = 3;
    public static final int NAME_FIELD_NUMBER = 3;
    private boolean hasName;
    private java.lang.String name_ = "";
    public boolean hasName() { return hasName; }
    public java.lang.String getName() { return name_; }
    
    // optional string platform = 4;
    public static final int PLATFORM_FIELD_NUMBER = 4;
    private boolean hasPlatform;
    private java.lang.String platform_ = "";
    public boolean hasPlatform() { return hasPlatform; }
    public java.lang.String getPlatform() { return platform_; }
    
    // optional int32 prior = 5;
    public static final int PRIOR_FIELD_NUMBER = 5;
    private boolean hasPrior;
    private int prior_ = 0;
    public boolean hasPrior() { return hasPrior; }
    public int getPrior() { return prior_; }
    
    // optional string budget = 6;
    public static final int BUDGET_FIELD_NUMBER = 6;
    private boolean hasBudget;
    private java.lang.String budget_ = "";
    public boolean hasBudget() { return hasBudget; }
    public java.lang.String getBudget() { return budget_; }
    
    // optional double budget_limit = 7;
    public static final int BUDGET_LIMIT_FIELD_NUMBER = 7;
    private boolean hasBudgetLimit;
    private double budgetLimit_ = 0D;
    public boolean hasBudgetLimit() { return hasBudgetLimit; }
    public double getBudgetLimit() { return budgetLimit_; }
    
    // optional string price_type = 8;
    public static final int PRICE_TYPE_FIELD_NUMBER = 8;
    private boolean hasPriceType;
    private java.lang.String priceType_ = "";
    public boolean hasPriceType() { return hasPriceType; }
    public java.lang.String getPriceType() { return priceType_; }
    
    // optional double cost_price = 9;
    public static final int COST_PRICE_FIELD_NUMBER = 9;
    private boolean hasCostPrice;
    private double costPrice_ = 0D;
    public boolean hasCostPrice() { return hasCostPrice; }
    public double getCostPrice() { return costPrice_; }
    
    // optional int64 start_time = 10;
    public static final int START_TIME_FIELD_NUMBER = 10;
    private boolean hasStartTime;
    private long startTime_ = 0L;
    public boolean hasStartTime() { return hasStartTime; }
    public long getStartTime() { return startTime_; }
    
    // optional int64 end_time = 11;
    public static final int END_TIME_FIELD_NUMBER = 11;
    private boolean hasEndTime;
    private long endTime_ = 0L;
    public boolean hasEndTime() { return hasEndTime; }
    public long getEndTime() { return endTime_; }
    
    // optional string channels = 12;
    public static final int CHANNELS_FIELD_NUMBER = 12;
    private boolean hasChannels;
    private java.lang.String channels_ = "";
    public boolean hasChannels() { return hasChannels; }
    public java.lang.String getChannels() { return channels_; }
    
    // optional string areas = 13;
    public static final int AREAS_FIELD_NUMBER = 13;
    private boolean hasAreas;
    private java.lang.String areas_ = "";
    public boolean hasAreas() { return hasAreas; }
    public java.lang.String getAreas() { return areas_; }
    
    // optional string networks = 14;
    public static final int NETWORKS_FIELD_NUMBER = 14;
    private boolean hasNetworks;
    private java.lang.String networks_ = "";
    public boolean hasNetworks() { return hasNetworks; }
    public java.lang.String getNetworks() { return networks_; }
    
    // optional string status = 15;
    public static final int STATUS_FIELD_NUMBER = 15;
    private boolean hasStatus;
    private java.lang.String status_ = "";
    public boolean hasStatus() { return hasStatus; }
    public java.lang.String getStatus() { return status_; }
    
    // optional int32 fixed_rank = 16;
    public static final int FIXED_RANK_FIELD_NUMBER = 16;
    private boolean hasFixedRank;
    private int fixedRank_ = 0;
    public boolean hasFixedRank() { return hasFixedRank; }
    public int getFixedRank() { return fixedRank_; }
    
    private void initFields() {
    }
    public final boolean isInitialized() {
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasId()) {
        output.writeInt32(1, getId());
      }
      if (hasAdOrderId()) {
        output.writeInt32(2, getAdOrderId());
      }
      if (hasName()) {
        output.writeString(3, getName());
      }
      if (hasPlatform()) {
        output.writeString(4, getPlatform());
      }
      if (hasPrior()) {
        output.writeInt32(5, getPrior());
      }
      if (hasBudget()) {
        output.writeString(6, getBudget());
      }
      if (hasBudgetLimit()) {
        output.writeDouble(7, getBudgetLimit());
      }
      if (hasPriceType()) {
        output.writeString(8, getPriceType());
      }
      if (hasCostPrice()) {
        output.writeDouble(9, getCostPrice());
      }
      if (hasStartTime()) {
        output.writeInt64(10, getStartTime());
      }
      if (hasEndTime()) {
        output.writeInt64(11, getEndTime());
      }
      if (hasChannels()) {
        output.writeString(12, getChannels());
      }
      if (hasAreas()) {
        output.writeString(13, getAreas());
      }
      if (hasNetworks()) {
        output.writeString(14, getNetworks());
      }
      if (hasStatus()) {
        output.writeString(15, getStatus());
      }
      if (hasFixedRank()) {
        output.writeInt32(16, getFixedRank());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasId()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, getId());
      }
      if (hasAdOrderId()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, getAdOrderId());
      }
      if (hasName()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(3, getName());
      }
      if (hasPlatform()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(4, getPlatform());
      }
      if (hasPrior()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, getPrior());
      }
      if (hasBudget()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(6, getBudget());
      }
      if (hasBudgetLimit()) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(7, getBudgetLimit());
      }
      if (hasPriceType()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(8, getPriceType());
      }
      if (hasCostPrice()) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(9, getCostPrice());
      }
      if (hasStartTime()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(10, getStartTime());
      }
      if (hasEndTime()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(11, getEndTime());
      }
      if (hasChannels()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(12, getChannels());
      }
      if (hasAreas()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(13, getAreas());
      }
      if (hasNetworks()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(14, getNetworks());
      }
      if (hasStatus()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(15, getStatus());
      }
      if (hasFixedRank()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(16, getFixedRank());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static com.umeng.ufp.core.domain.protobuf.AdProtos.AdEntry parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.umeng.ufp.core.domain.protobuf.AdProtos.AdEntry parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.umeng.ufp.core.domain.protobuf.AdProtos.AdEntry parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.umeng.ufp.core.domain.protobuf.AdProtos.AdEntry parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.umeng.ufp.core.domain.protobuf.AdProtos.AdEntry parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.umeng.ufp.core.domain.protobuf.AdProtos.AdEntry parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.umeng.ufp.core.domain.protobuf.AdProtos.AdEntry parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.umeng.ufp.core.domain.protobuf.AdProtos.AdEntry parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.umeng.ufp.core.domain.protobuf.AdProtos.AdEntry parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.umeng.ufp.core.domain.protobuf.AdProtos.AdEntry parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.umeng.ufp.core.domain.protobuf.AdProtos.AdEntry prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private com.umeng.ufp.core.domain.protobuf.AdProtos.AdEntry result;
      
      // Construct using com.umeng.ufp.core.domain.protobuf.AdProtos.AdEntry.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new com.umeng.ufp.core.domain.protobuf.AdProtos.AdEntry();
        return builder;
      }
      
      protected com.umeng.ufp.core.domain.protobuf.AdProtos.AdEntry internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new com.umeng.ufp.core.domain.protobuf.AdProtos.AdEntry();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.umeng.ufp.core.domain.protobuf.AdProtos.AdEntry.getDescriptor();
      }
      
      public com.umeng.ufp.core.domain.protobuf.AdProtos.AdEntry getDefaultInstanceForType() {
        return com.umeng.ufp.core.domain.protobuf.AdProtos.AdEntry.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public com.umeng.ufp.core.domain.protobuf.AdProtos.AdEntry build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private com.umeng.ufp.core.domain.protobuf.AdProtos.AdEntry buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.umeng.ufp.core.domain.protobuf.AdProtos.AdEntry buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        com.umeng.ufp.core.domain.protobuf.AdProtos.AdEntry returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.umeng.ufp.core.domain.protobuf.AdProtos.AdEntry) {
          return mergeFrom((com.umeng.ufp.core.domain.protobuf.AdProtos.AdEntry)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.umeng.ufp.core.domain.protobuf.AdProtos.AdEntry other) {
        if (other == com.umeng.ufp.core.domain.protobuf.AdProtos.AdEntry.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasAdOrderId()) {
          setAdOrderId(other.getAdOrderId());
        }
        if (other.hasName()) {
          setName(other.getName());
        }
        if (other.hasPlatform()) {
          setPlatform(other.getPlatform());
        }
        if (other.hasPrior()) {
          setPrior(other.getPrior());
        }
        if (other.hasBudget()) {
          setBudget(other.getBudget());
        }
        if (other.hasBudgetLimit()) {
          setBudgetLimit(other.getBudgetLimit());
        }
        if (other.hasPriceType()) {
          setPriceType(other.getPriceType());
        }
        if (other.hasCostPrice()) {
          setCostPrice(other.getCostPrice());
        }
        if (other.hasStartTime()) {
          setStartTime(other.getStartTime());
        }
        if (other.hasEndTime()) {
          setEndTime(other.getEndTime());
        }
        if (other.hasChannels()) {
          setChannels(other.getChannels());
        }
        if (other.hasAreas()) {
          setAreas(other.getAreas());
        }
        if (other.hasNetworks()) {
          setNetworks(other.getNetworks());
        }
        if (other.hasStatus()) {
          setStatus(other.getStatus());
        }
        if (other.hasFixedRank()) {
          setFixedRank(other.getFixedRank());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 8: {
              setId(input.readInt32());
              break;
            }
            case 16: {
              setAdOrderId(input.readInt32());
              break;
            }
            case 26: {
              setName(input.readString());
              break;
            }
            case 34: {
              setPlatform(input.readString());
              break;
            }
            case 40: {
              setPrior(input.readInt32());
              break;
            }
            case 50: {
              setBudget(input.readString());
              break;
            }
            case 57: {
              setBudgetLimit(input.readDouble());
              break;
            }
            case 66: {
              setPriceType(input.readString());
              break;
            }
            case 73: {
              setCostPrice(input.readDouble());
              break;
            }
            case 80: {
              setStartTime(input.readInt64());
              break;
            }
            case 88: {
              setEndTime(input.readInt64());
              break;
            }
            case 98: {
              setChannels(input.readString());
              break;
            }
            case 106: {
              setAreas(input.readString());
              break;
            }
            case 114: {
              setNetworks(input.readString());
              break;
            }
            case 122: {
              setStatus(input.readString());
              break;
            }
            case 128: {
              setFixedRank(input.readInt32());
              break;
            }
          }
        }
      }
      
      
      // optional int32 id = 1;
      public boolean hasId() {
        return result.hasId();
      }
      public int getId() {
        return result.getId();
      }
      public Builder setId(int value) {
        result.hasId = true;
        result.id_ = value;
        return this;
      }
      public Builder clearId() {
        result.hasId = false;
        result.id_ = 0;
        return this;
      }
      
      // optional int32 ad_order_id = 2;
      public boolean hasAdOrderId() {
        return result.hasAdOrderId();
      }
      public int getAdOrderId() {
        return result.getAdOrderId();
      }
      public Builder setAdOrderId(int value) {
        result.hasAdOrderId = true;
        result.adOrderId_ = value;
        return this;
      }
      public Builder clearAdOrderId() {
        result.hasAdOrderId = false;
        result.adOrderId_ = 0;
        return this;
      }
      
      // optional string name = 3;
      public boolean hasName() {
        return result.hasName();
      }
      public java.lang.String getName() {
        return result.getName();
      }
      public Builder setName(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasName = true;
        result.name_ = value;
        return this;
      }
      public Builder clearName() {
        result.hasName = false;
        result.name_ = getDefaultInstance().getName();
        return this;
      }
      
      // optional string platform = 4;
      public boolean hasPlatform() {
        return result.hasPlatform();
      }
      public java.lang.String getPlatform() {
        return result.getPlatform();
      }
      public Builder setPlatform(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasPlatform = true;
        result.platform_ = value;
        return this;
      }
      public Builder clearPlatform() {
        result.hasPlatform = false;
        result.platform_ = getDefaultInstance().getPlatform();
        return this;
      }
      
      // optional int32 prior = 5;
      public boolean hasPrior() {
        return result.hasPrior();
      }
      public int getPrior() {
        return result.getPrior();
      }
      public Builder setPrior(int value) {
        result.hasPrior = true;
        result.prior_ = value;
        return this;
      }
      public Builder clearPrior() {
        result.hasPrior = false;
        result.prior_ = 0;
        return this;
      }
      
      // optional string budget = 6;
      public boolean hasBudget() {
        return result.hasBudget();
      }
      public java.lang.String getBudget() {
        return result.getBudget();
      }
      public Builder setBudget(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasBudget = true;
        result.budget_ = value;
        return this;
      }
      public Builder clearBudget() {
        result.hasBudget = false;
        result.budget_ = getDefaultInstance().getBudget();
        return this;
      }
      
      // optional double budget_limit = 7;
      public boolean hasBudgetLimit() {
        return result.hasBudgetLimit();
      }
      public double getBudgetLimit() {
        return result.getBudgetLimit();
      }
      public Builder setBudgetLimit(double value) {
        result.hasBudgetLimit = true;
        result.budgetLimit_ = value;
        return this;
      }
      public Builder clearBudgetLimit() {
        result.hasBudgetLimit = false;
        result.budgetLimit_ = 0D;
        return this;
      }
      
      // optional string price_type = 8;
      public boolean hasPriceType() {
        return result.hasPriceType();
      }
      public java.lang.String getPriceType() {
        return result.getPriceType();
      }
      public Builder setPriceType(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasPriceType = true;
        result.priceType_ = value;
        return this;
      }
      public Builder clearPriceType() {
        result.hasPriceType = false;
        result.priceType_ = getDefaultInstance().getPriceType();
        return this;
      }
      
      // optional double cost_price = 9;
      public boolean hasCostPrice() {
        return result.hasCostPrice();
      }
      public double getCostPrice() {
        return result.getCostPrice();
      }
      public Builder setCostPrice(double value) {
        result.hasCostPrice = true;
        result.costPrice_ = value;
        return this;
      }
      public Builder clearCostPrice() {
        result.hasCostPrice = false;
        result.costPrice_ = 0D;
        return this;
      }
      
      // optional int64 start_time = 10;
      public boolean hasStartTime() {
        return result.hasStartTime();
      }
      public long getStartTime() {
        return result.getStartTime();
      }
      public Builder setStartTime(long value) {
        result.hasStartTime = true;
        result.startTime_ = value;
        return this;
      }
      public Builder clearStartTime() {
        result.hasStartTime = false;
        result.startTime_ = 0L;
        return this;
      }
      
      // optional int64 end_time = 11;
      public boolean hasEndTime() {
        return result.hasEndTime();
      }
      public long getEndTime() {
        return result.getEndTime();
      }
      public Builder setEndTime(long value) {
        result.hasEndTime = true;
        result.endTime_ = value;
        return this;
      }
      public Builder clearEndTime() {
        result.hasEndTime = false;
        result.endTime_ = 0L;
        return this;
      }
      
      // optional string channels = 12;
      public boolean hasChannels() {
        return result.hasChannels();
      }
      public java.lang.String getChannels() {
        return result.getChannels();
      }
      public Builder setChannels(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasChannels = true;
        result.channels_ = value;
        return this;
      }
      public Builder clearChannels() {
        result.hasChannels = false;
        result.channels_ = getDefaultInstance().getChannels();
        return this;
      }
      
      // optional string areas = 13;
      public boolean hasAreas() {
        return result.hasAreas();
      }
      public java.lang.String getAreas() {
        return result.getAreas();
      }
      public Builder setAreas(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasAreas = true;
        result.areas_ = value;
        return this;
      }
      public Builder clearAreas() {
        result.hasAreas = false;
        result.areas_ = getDefaultInstance().getAreas();
        return this;
      }
      
      // optional string networks = 14;
      public boolean hasNetworks() {
        return result.hasNetworks();
      }
      public java.lang.String getNetworks() {
        return result.getNetworks();
      }
      public Builder setNetworks(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasNetworks = true;
        result.networks_ = value;
        return this;
      }
      public Builder clearNetworks() {
        result.hasNetworks = false;
        result.networks_ = getDefaultInstance().getNetworks();
        return this;
      }
      
      // optional string status = 15;
      public boolean hasStatus() {
        return result.hasStatus();
      }
      public java.lang.String getStatus() {
        return result.getStatus();
      }
      public Builder setStatus(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasStatus = true;
        result.status_ = value;
        return this;
      }
      public Builder clearStatus() {
        result.hasStatus = false;
        result.status_ = getDefaultInstance().getStatus();
        return this;
      }
      
      // optional int32 fixed_rank = 16;
      public boolean hasFixedRank() {
        return result.hasFixedRank();
      }
      public int getFixedRank() {
        return result.getFixedRank();
      }
      public Builder setFixedRank(int value) {
        result.hasFixedRank = true;
        result.fixedRank_ = value;
        return this;
      }
      public Builder clearFixedRank() {
        result.hasFixedRank = false;
        result.fixedRank_ = 0;
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:com.umeng.ufp.core.domain.protobuf.AdEntry)
    }
    
    static {
      defaultInstance = new AdEntry(true);
      com.umeng.ufp.core.domain.protobuf.AdProtos.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.umeng.ufp.core.domain.protobuf.AdEntry)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_umeng_ufp_core_domain_protobuf_AdEntry_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_umeng_ufp_core_domain_protobuf_AdEntry_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016ad_entry.proto\022\"com.umeng.ufp.core.dom" +
      "ain.protobuf\"\244\002\n\007AdEntry\022\n\n\002id\030\001 \001(\005\022\023\n\013" +
      "ad_order_id\030\002 \001(\005\022\014\n\004name\030\003 \001(\t\022\020\n\010platf" +
      "orm\030\004 \001(\t\022\r\n\005prior\030\005 \001(\005\022\016\n\006budget\030\006 \001(\t" +
      "\022\024\n\014budget_limit\030\007 \001(\001\022\022\n\nprice_type\030\010 \001" +
      "(\t\022\022\n\ncost_price\030\t \001(\001\022\022\n\nstart_time\030\n \001" +
      "(\003\022\020\n\010end_time\030\013 \001(\003\022\020\n\010channels\030\014 \001(\t\022\r" +
      "\n\005areas\030\r \001(\t\022\020\n\010networks\030\016 \001(\t\022\016\n\006statu" +
      "s\030\017 \001(\t\022\022\n\nfixed_rank\030\020 \001(\005B.\n\"com.umeng" +
      ".ufp.core.domain.protobufB\010AdProtos"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_umeng_ufp_core_domain_protobuf_AdEntry_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_umeng_ufp_core_domain_protobuf_AdEntry_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_umeng_ufp_core_domain_protobuf_AdEntry_descriptor,
              new java.lang.String[] { "Id", "AdOrderId", "Name", "Platform", "Prior", "Budget", "BudgetLimit", "PriceType", "CostPrice", "StartTime", "EndTime", "Channels", "Areas", "Networks", "Status", "FixedRank", },
              com.umeng.ufp.core.domain.protobuf.AdProtos.AdEntry.class,
              com.umeng.ufp.core.domain.protobuf.AdProtos.AdEntry.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  public static void internalForceInit() {}
  
  // @@protoc_insertion_point(outer_class_scope)
}
