// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ad_slot_entry.proto

package com.umeng.ufp.core.domain.protobuf;

public final class AdSlotProtos {
  private AdSlotProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public static final class AdSlotEntry extends
      com.google.protobuf.GeneratedMessage {
    // Use AdSlotEntry.newBuilder() to construct.
    private AdSlotEntry() {
      initFields();
    }
    private AdSlotEntry(boolean noInit) {}
    
    private static final AdSlotEntry defaultInstance;
    public static AdSlotEntry getDefaultInstance() {
      return defaultInstance;
    }
    
    public AdSlotEntry getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.umeng.ufp.core.domain.protobuf.AdSlotProtos.internal_static_com_umeng_ufp_core_domain_protobuf_AdSlotEntry_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.umeng.ufp.core.domain.protobuf.AdSlotProtos.internal_static_com_umeng_ufp_core_domain_protobuf_AdSlotEntry_fieldAccessorTable;
    }
    
    // optional int32 id = 1;
    public static final int ID_FIELD_NUMBER = 1;
    private boolean hasId;
    private int id_ = 0;
    public boolean hasId() { return hasId; }
    public int getId() { return id_; }
    
    // optional int32 app_id = 2;
    public static final int APP_ID_FIELD_NUMBER = 2;
    private boolean hasAppId;
    private int appId_ = 0;
    public boolean hasAppId() { return hasAppId; }
    public int getAppId() { return appId_; }
    
    // optional string name = 3;
    public static final int NAME_FIELD_NUMBER = 3;
    private boolean hasName;
    private java.lang.String name_ = "";
    public boolean hasName() { return hasName; }
    public java.lang.String getName() { return name_; }
    
    // optional string landing_type = 4;
    public static final int LANDING_TYPE_FIELD_NUMBER = 4;
    private boolean hasLandingType;
    private java.lang.String landingType_ = "";
    public boolean hasLandingType() { return hasLandingType; }
    public java.lang.String getLandingType() { return landingType_; }
    
    // optional string landing_size = 5;
    public static final int LANDING_SIZE_FIELD_NUMBER = 5;
    private boolean hasLandingSize;
    private java.lang.String landingSize_ = "";
    public boolean hasLandingSize() { return hasLandingSize; }
    public java.lang.String getLandingSize() { return landingSize_; }
    
    // optional string landing_images = 6;
    public static final int LANDING_IMAGES_FIELD_NUMBER = 6;
    private boolean hasLandingImages;
    private java.lang.String landingImages_ = "";
    public boolean hasLandingImages() { return hasLandingImages; }
    public java.lang.String getLandingImages() { return landingImages_; }
    
    // optional string platform = 7;
    public static final int PLATFORM_FIELD_NUMBER = 7;
    private boolean hasPlatform;
    private java.lang.String platform_ = "";
    public boolean hasPlatform() { return hasPlatform; }
    public java.lang.String getPlatform() { return platform_; }
    
    // optional string device = 8;
    public static final int DEVICE_FIELD_NUMBER = 8;
    private boolean hasDevice;
    private java.lang.String device_ = "";
    public boolean hasDevice() { return hasDevice; }
    public java.lang.String getDevice() { return device_; }
    
    // optional string channels = 9;
    public static final int CHANNELS_FIELD_NUMBER = 9;
    private boolean hasChannels;
    private java.lang.String channels_ = "";
    public boolean hasChannels() { return hasChannels; }
    public java.lang.String getChannels() { return channels_; }
    
    // optional string areas = 10;
    public static final int AREAS_FIELD_NUMBER = 10;
    private boolean hasAreas;
    private java.lang.String areas_ = "";
    public boolean hasAreas() { return hasAreas; }
    public java.lang.String getAreas() { return areas_; }
    
    // optional string text_size = 11;
    public static final int TEXT_SIZE_FIELD_NUMBER = 11;
    private boolean hasTextSize;
    private java.lang.String textSize_ = "";
    public boolean hasTextSize() { return hasTextSize; }
    public java.lang.String getTextSize() { return textSize_; }
    
    // optional string display_strategy = 12;
    public static final int DISPLAY_STRATEGY_FIELD_NUMBER = 12;
    private boolean hasDisplayStrategy;
    private java.lang.String displayStrategy_ = "";
    public boolean hasDisplayStrategy() { return hasDisplayStrategy; }
    public java.lang.String getDisplayStrategy() { return displayStrategy_; }
    
    // optional string timeslots = 13;
    public static final int TIMESLOTS_FIELD_NUMBER = 13;
    private boolean hasTimeslots;
    private java.lang.String timeslots_ = "";
    public boolean hasTimeslots() { return hasTimeslots; }
    public java.lang.String getTimeslots() { return timeslots_; }
    
    // optional string template = 14;
    public static final int TEMPLATE_FIELD_NUMBER = 14;
    private boolean hasTemplate;
    private java.lang.String template_ = "";
    public boolean hasTemplate() { return hasTemplate; }
    public java.lang.String getTemplate() { return template_; }
    
    // optional string anim_in = 15;
    public static final int ANIM_IN_FIELD_NUMBER = 15;
    private boolean hasAnimIn;
    private java.lang.String animIn_ = "";
    public boolean hasAnimIn() { return hasAnimIn; }
    public java.lang.String getAnimIn() { return animIn_; }
    
    // optional string enable_preload = 16;
    public static final int ENABLE_PRELOAD_FIELD_NUMBER = 16;
    private boolean hasEnablePreload;
    private java.lang.String enablePreload_ = "";
    public boolean hasEnablePreload() { return hasEnablePreload; }
    public java.lang.String getEnablePreload() { return enablePreload_; }
    
    // optional string enable_page = 17;
    public static final int ENABLE_PAGE_FIELD_NUMBER = 17;
    private boolean hasEnablePage;
    private java.lang.String enablePage_ = "";
    public boolean hasEnablePage() { return hasEnablePage; }
    public java.lang.String getEnablePage() { return enablePage_; }
    
    // optional string status = 18;
    public static final int STATUS_FIELD_NUMBER = 18;
    private boolean hasStatus;
    private java.lang.String status_ = "";
    public boolean hasStatus() { return hasStatus; }
    public java.lang.String getStatus() { return status_; }
    
    // optional string ad_network_strategy = 19;
    public static final int AD_NETWORK_STRATEGY_FIELD_NUMBER = 19;
    private boolean hasAdNetworkStrategy;
    private java.lang.String adNetworkStrategy_ = "";
    public boolean hasAdNetworkStrategy() { return hasAdNetworkStrategy; }
    public java.lang.String getAdNetworkStrategy() { return adNetworkStrategy_; }
    
    // optional bool xp_enable = 20;
    public static final int XP_ENABLE_FIELD_NUMBER = 20;
    private boolean hasXpEnable;
    private boolean xpEnable_ = false;
    public boolean hasXpEnable() { return hasXpEnable; }
    public boolean getXpEnable() { return xpEnable_; }
    
    // optional int32 xp_percent = 21;
    public static final int XP_PERCENT_FIELD_NUMBER = 21;
    private boolean hasXpPercent;
    private int xpPercent_ = 0;
    public boolean hasXpPercent() { return hasXpPercent; }
    public int getXpPercent() { return xpPercent_; }
    
    // optional string appkey = 22;
    public static final int APPKEY_FIELD_NUMBER = 22;
    private boolean hasAppkey;
    private java.lang.String appkey_ = "";
    public boolean hasAppkey() { return hasAppkey; }
    public java.lang.String getAppkey() { return appkey_; }
    
    // optional bool uads_enable = 23;
    public static final int UADS_ENABLE_FIELD_NUMBER = 23;
    private boolean hasUadsEnable;
    private boolean uadsEnable_ = false;
    public boolean hasUadsEnable() { return hasUadsEnable; }
    public boolean getUadsEnable() { return uadsEnable_; }
    
    // optional int32 uads_percent = 24;
    public static final int UADS_PERCENT_FIELD_NUMBER = 24;
    private boolean hasUadsPercent;
    private int uadsPercent_ = 0;
    public boolean hasUadsPercent() { return hasUadsPercent; }
    public int getUadsPercent() { return uadsPercent_; }
    
    // optional string uads_key = 25;
    public static final int UADS_KEY_FIELD_NUMBER = 25;
    private boolean hasUadsKey;
    private java.lang.String uadsKey_ = "";
    public boolean hasUadsKey() { return hasUadsKey; }
    public java.lang.String getUadsKey() { return uadsKey_; }
    
    // optional string uads_key2 = 26;
    public static final int UADS_KEY2_FIELD_NUMBER = 26;
    private boolean hasUadsKey2;
    private java.lang.String uadsKey2_ = "";
    public boolean hasUadsKey2() { return hasUadsKey2; }
    public java.lang.String getUadsKey2() { return uadsKey2_; }
    
    private void initFields() {
    }
    public final boolean isInitialized() {
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasId()) {
        output.writeInt32(1, getId());
      }
      if (hasAppId()) {
        output.writeInt32(2, getAppId());
      }
      if (hasName()) {
        output.writeString(3, getName());
      }
      if (hasLandingType()) {
        output.writeString(4, getLandingType());
      }
      if (hasLandingSize()) {
        output.writeString(5, getLandingSize());
      }
      if (hasLandingImages()) {
        output.writeString(6, getLandingImages());
      }
      if (hasPlatform()) {
        output.writeString(7, getPlatform());
      }
      if (hasDevice()) {
        output.writeString(8, getDevice());
      }
      if (hasChannels()) {
        output.writeString(9, getChannels());
      }
      if (hasAreas()) {
        output.writeString(10, getAreas());
      }
      if (hasTextSize()) {
        output.writeString(11, getTextSize());
      }
      if (hasDisplayStrategy()) {
        output.writeString(12, getDisplayStrategy());
      }
      if (hasTimeslots()) {
        output.writeString(13, getTimeslots());
      }
      if (hasTemplate()) {
        output.writeString(14, getTemplate());
      }
      if (hasAnimIn()) {
        output.writeString(15, getAnimIn());
      }
      if (hasEnablePreload()) {
        output.writeString(16, getEnablePreload());
      }
      if (hasEnablePage()) {
        output.writeString(17, getEnablePage());
      }
      if (hasStatus()) {
        output.writeString(18, getStatus());
      }
      if (hasAdNetworkStrategy()) {
        output.writeString(19, getAdNetworkStrategy());
      }
      if (hasXpEnable()) {
        output.writeBool(20, getXpEnable());
      }
      if (hasXpPercent()) {
        output.writeInt32(21, getXpPercent());
      }
      if (hasAppkey()) {
        output.writeString(22, getAppkey());
      }
      if (hasUadsEnable()) {
        output.writeBool(23, getUadsEnable());
      }
      if (hasUadsPercent()) {
        output.writeInt32(24, getUadsPercent());
      }
      if (hasUadsKey()) {
        output.writeString(25, getUadsKey());
      }
      if (hasUadsKey2()) {
        output.writeString(26, getUadsKey2());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasId()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, getId());
      }
      if (hasAppId()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, getAppId());
      }
      if (hasName()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(3, getName());
      }
      if (hasLandingType()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(4, getLandingType());
      }
      if (hasLandingSize()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(5, getLandingSize());
      }
      if (hasLandingImages()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(6, getLandingImages());
      }
      if (hasPlatform()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(7, getPlatform());
      }
      if (hasDevice()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(8, getDevice());
      }
      if (hasChannels()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(9, getChannels());
      }
      if (hasAreas()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(10, getAreas());
      }
      if (hasTextSize()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(11, getTextSize());
      }
      if (hasDisplayStrategy()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(12, getDisplayStrategy());
      }
      if (hasTimeslots()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(13, getTimeslots());
      }
      if (hasTemplate()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(14, getTemplate());
      }
      if (hasAnimIn()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(15, getAnimIn());
      }
      if (hasEnablePreload()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(16, getEnablePreload());
      }
      if (hasEnablePage()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(17, getEnablePage());
      }
      if (hasStatus()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(18, getStatus());
      }
      if (hasAdNetworkStrategy()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(19, getAdNetworkStrategy());
      }
      if (hasXpEnable()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(20, getXpEnable());
      }
      if (hasXpPercent()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(21, getXpPercent());
      }
      if (hasAppkey()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(22, getAppkey());
      }
      if (hasUadsEnable()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(23, getUadsEnable());
      }
      if (hasUadsPercent()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(24, getUadsPercent());
      }
      if (hasUadsKey()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(25, getUadsKey());
      }
      if (hasUadsKey2()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(26, getUadsKey2());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static com.umeng.ufp.core.domain.protobuf.AdSlotProtos.AdSlotEntry parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.umeng.ufp.core.domain.protobuf.AdSlotProtos.AdSlotEntry parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.umeng.ufp.core.domain.protobuf.AdSlotProtos.AdSlotEntry parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.umeng.ufp.core.domain.protobuf.AdSlotProtos.AdSlotEntry parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.umeng.ufp.core.domain.protobuf.AdSlotProtos.AdSlotEntry parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.umeng.ufp.core.domain.protobuf.AdSlotProtos.AdSlotEntry parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.umeng.ufp.core.domain.protobuf.AdSlotProtos.AdSlotEntry parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.umeng.ufp.core.domain.protobuf.AdSlotProtos.AdSlotEntry parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.umeng.ufp.core.domain.protobuf.AdSlotProtos.AdSlotEntry parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.umeng.ufp.core.domain.protobuf.AdSlotProtos.AdSlotEntry parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.umeng.ufp.core.domain.protobuf.AdSlotProtos.AdSlotEntry prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private com.umeng.ufp.core.domain.protobuf.AdSlotProtos.AdSlotEntry result;
      
      // Construct using com.umeng.ufp.core.domain.protobuf.AdSlotProtos.AdSlotEntry.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new com.umeng.ufp.core.domain.protobuf.AdSlotProtos.AdSlotEntry();
        return builder;
      }
      
      protected com.umeng.ufp.core.domain.protobuf.AdSlotProtos.AdSlotEntry internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new com.umeng.ufp.core.domain.protobuf.AdSlotProtos.AdSlotEntry();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.umeng.ufp.core.domain.protobuf.AdSlotProtos.AdSlotEntry.getDescriptor();
      }
      
      public com.umeng.ufp.core.domain.protobuf.AdSlotProtos.AdSlotEntry getDefaultInstanceForType() {
        return com.umeng.ufp.core.domain.protobuf.AdSlotProtos.AdSlotEntry.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public com.umeng.ufp.core.domain.protobuf.AdSlotProtos.AdSlotEntry build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private com.umeng.ufp.core.domain.protobuf.AdSlotProtos.AdSlotEntry buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.umeng.ufp.core.domain.protobuf.AdSlotProtos.AdSlotEntry buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        com.umeng.ufp.core.domain.protobuf.AdSlotProtos.AdSlotEntry returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.umeng.ufp.core.domain.protobuf.AdSlotProtos.AdSlotEntry) {
          return mergeFrom((com.umeng.ufp.core.domain.protobuf.AdSlotProtos.AdSlotEntry)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.umeng.ufp.core.domain.protobuf.AdSlotProtos.AdSlotEntry other) {
        if (other == com.umeng.ufp.core.domain.protobuf.AdSlotProtos.AdSlotEntry.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasAppId()) {
          setAppId(other.getAppId());
        }
        if (other.hasName()) {
          setName(other.getName());
        }
        if (other.hasLandingType()) {
          setLandingType(other.getLandingType());
        }
        if (other.hasLandingSize()) {
          setLandingSize(other.getLandingSize());
        }
        if (other.hasLandingImages()) {
          setLandingImages(other.getLandingImages());
        }
        if (other.hasPlatform()) {
          setPlatform(other.getPlatform());
        }
        if (other.hasDevice()) {
          setDevice(other.getDevice());
        }
        if (other.hasChannels()) {
          setChannels(other.getChannels());
        }
        if (other.hasAreas()) {
          setAreas(other.getAreas());
        }
        if (other.hasTextSize()) {
          setTextSize(other.getTextSize());
        }
        if (other.hasDisplayStrategy()) {
          setDisplayStrategy(other.getDisplayStrategy());
        }
        if (other.hasTimeslots()) {
          setTimeslots(other.getTimeslots());
        }
        if (other.hasTemplate()) {
          setTemplate(other.getTemplate());
        }
        if (other.hasAnimIn()) {
          setAnimIn(other.getAnimIn());
        }
        if (other.hasEnablePreload()) {
          setEnablePreload(other.getEnablePreload());
        }
        if (other.hasEnablePage()) {
          setEnablePage(other.getEnablePage());
        }
        if (other.hasStatus()) {
          setStatus(other.getStatus());
        }
        if (other.hasAdNetworkStrategy()) {
          setAdNetworkStrategy(other.getAdNetworkStrategy());
        }
        if (other.hasXpEnable()) {
          setXpEnable(other.getXpEnable());
        }
        if (other.hasXpPercent()) {
          setXpPercent(other.getXpPercent());
        }
        if (other.hasAppkey()) {
          setAppkey(other.getAppkey());
        }
        if (other.hasUadsEnable()) {
          setUadsEnable(other.getUadsEnable());
        }
        if (other.hasUadsPercent()) {
          setUadsPercent(other.getUadsPercent());
        }
        if (other.hasUadsKey()) {
          setUadsKey(other.getUadsKey());
        }
        if (other.hasUadsKey2()) {
          setUadsKey2(other.getUadsKey2());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 8: {
              setId(input.readInt32());
              break;
            }
            case 16: {
              setAppId(input.readInt32());
              break;
            }
            case 26: {
              setName(input.readString());
              break;
            }
            case 34: {
              setLandingType(input.readString());
              break;
            }
            case 42: {
              setLandingSize(input.readString());
              break;
            }
            case 50: {
              setLandingImages(input.readString());
              break;
            }
            case 58: {
              setPlatform(input.readString());
              break;
            }
            case 66: {
              setDevice(input.readString());
              break;
            }
            case 74: {
              setChannels(input.readString());
              break;
            }
            case 82: {
              setAreas(input.readString());
              break;
            }
            case 90: {
              setTextSize(input.readString());
              break;
            }
            case 98: {
              setDisplayStrategy(input.readString());
              break;
            }
            case 106: {
              setTimeslots(input.readString());
              break;
            }
            case 114: {
              setTemplate(input.readString());
              break;
            }
            case 122: {
              setAnimIn(input.readString());
              break;
            }
            case 130: {
              setEnablePreload(input.readString());
              break;
            }
            case 138: {
              setEnablePage(input.readString());
              break;
            }
            case 146: {
              setStatus(input.readString());
              break;
            }
            case 154: {
              setAdNetworkStrategy(input.readString());
              break;
            }
            case 160: {
              setXpEnable(input.readBool());
              break;
            }
            case 168: {
              setXpPercent(input.readInt32());
              break;
            }
            case 178: {
              setAppkey(input.readString());
              break;
            }
            case 184: {
              setUadsEnable(input.readBool());
              break;
            }
            case 192: {
              setUadsPercent(input.readInt32());
              break;
            }
            case 202: {
              setUadsKey(input.readString());
              break;
            }
            case 210: {
              setUadsKey2(input.readString());
              break;
            }
          }
        }
      }
      
      
      // optional int32 id = 1;
      public boolean hasId() {
        return result.hasId();
      }
      public int getId() {
        return result.getId();
      }
      public Builder setId(int value) {
        result.hasId = true;
        result.id_ = value;
        return this;
      }
      public Builder clearId() {
        result.hasId = false;
        result.id_ = 0;
        return this;
      }
      
      // optional int32 app_id = 2;
      public boolean hasAppId() {
        return result.hasAppId();
      }
      public int getAppId() {
        return result.getAppId();
      }
      public Builder setAppId(int value) {
        result.hasAppId = true;
        result.appId_ = value;
        return this;
      }
      public Builder clearAppId() {
        result.hasAppId = false;
        result.appId_ = 0;
        return this;
      }
      
      // optional string name = 3;
      public boolean hasName() {
        return result.hasName();
      }
      public java.lang.String getName() {
        return result.getName();
      }
      public Builder setName(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasName = true;
        result.name_ = value;
        return this;
      }
      public Builder clearName() {
        result.hasName = false;
        result.name_ = getDefaultInstance().getName();
        return this;
      }
      
      // optional string landing_type = 4;
      public boolean hasLandingType() {
        return result.hasLandingType();
      }
      public java.lang.String getLandingType() {
        return result.getLandingType();
      }
      public Builder setLandingType(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasLandingType = true;
        result.landingType_ = value;
        return this;
      }
      public Builder clearLandingType() {
        result.hasLandingType = false;
        result.landingType_ = getDefaultInstance().getLandingType();
        return this;
      }
      
      // optional string landing_size = 5;
      public boolean hasLandingSize() {
        return result.hasLandingSize();
      }
      public java.lang.String getLandingSize() {
        return result.getLandingSize();
      }
      public Builder setLandingSize(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasLandingSize = true;
        result.landingSize_ = value;
        return this;
      }
      public Builder clearLandingSize() {
        result.hasLandingSize = false;
        result.landingSize_ = getDefaultInstance().getLandingSize();
        return this;
      }
      
      // optional string landing_images = 6;
      public boolean hasLandingImages() {
        return result.hasLandingImages();
      }
      public java.lang.String getLandingImages() {
        return result.getLandingImages();
      }
      public Builder setLandingImages(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasLandingImages = true;
        result.landingImages_ = value;
        return this;
      }
      public Builder clearLandingImages() {
        result.hasLandingImages = false;
        result.landingImages_ = getDefaultInstance().getLandingImages();
        return this;
      }
      
      // optional string platform = 7;
      public boolean hasPlatform() {
        return result.hasPlatform();
      }
      public java.lang.String getPlatform() {
        return result.getPlatform();
      }
      public Builder setPlatform(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasPlatform = true;
        result.platform_ = value;
        return this;
      }
      public Builder clearPlatform() {
        result.hasPlatform = false;
        result.platform_ = getDefaultInstance().getPlatform();
        return this;
      }
      
      // optional string device = 8;
      public boolean hasDevice() {
        return result.hasDevice();
      }
      public java.lang.String getDevice() {
        return result.getDevice();
      }
      public Builder setDevice(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasDevice = true;
        result.device_ = value;
        return this;
      }
      public Builder clearDevice() {
        result.hasDevice = false;
        result.device_ = getDefaultInstance().getDevice();
        return this;
      }
      
      // optional string channels = 9;
      public boolean hasChannels() {
        return result.hasChannels();
      }
      public java.lang.String getChannels() {
        return result.getChannels();
      }
      public Builder setChannels(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasChannels = true;
        result.channels_ = value;
        return this;
      }
      public Builder clearChannels() {
        result.hasChannels = false;
        result.channels_ = getDefaultInstance().getChannels();
        return this;
      }
      
      // optional string areas = 10;
      public boolean hasAreas() {
        return result.hasAreas();
      }
      public java.lang.String getAreas() {
        return result.getAreas();
      }
      public Builder setAreas(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasAreas = true;
        result.areas_ = value;
        return this;
      }
      public Builder clearAreas() {
        result.hasAreas = false;
        result.areas_ = getDefaultInstance().getAreas();
        return this;
      }
      
      // optional string text_size = 11;
      public boolean hasTextSize() {
        return result.hasTextSize();
      }
      public java.lang.String getTextSize() {
        return result.getTextSize();
      }
      public Builder setTextSize(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasTextSize = true;
        result.textSize_ = value;
        return this;
      }
      public Builder clearTextSize() {
        result.hasTextSize = false;
        result.textSize_ = getDefaultInstance().getTextSize();
        return this;
      }
      
      // optional string display_strategy = 12;
      public boolean hasDisplayStrategy() {
        return result.hasDisplayStrategy();
      }
      public java.lang.String getDisplayStrategy() {
        return result.getDisplayStrategy();
      }
      public Builder setDisplayStrategy(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasDisplayStrategy = true;
        result.displayStrategy_ = value;
        return this;
      }
      public Builder clearDisplayStrategy() {
        result.hasDisplayStrategy = false;
        result.displayStrategy_ = getDefaultInstance().getDisplayStrategy();
        return this;
      }
      
      // optional string timeslots = 13;
      public boolean hasTimeslots() {
        return result.hasTimeslots();
      }
      public java.lang.String getTimeslots() {
        return result.getTimeslots();
      }
      public Builder setTimeslots(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasTimeslots = true;
        result.timeslots_ = value;
        return this;
      }
      public Builder clearTimeslots() {
        result.hasTimeslots = false;
        result.timeslots_ = getDefaultInstance().getTimeslots();
        return this;
      }
      
      // optional string template = 14;
      public boolean hasTemplate() {
        return result.hasTemplate();
      }
      public java.lang.String getTemplate() {
        return result.getTemplate();
      }
      public Builder setTemplate(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasTemplate = true;
        result.template_ = value;
        return this;
      }
      public Builder clearTemplate() {
        result.hasTemplate = false;
        result.template_ = getDefaultInstance().getTemplate();
        return this;
      }
      
      // optional string anim_in = 15;
      public boolean hasAnimIn() {
        return result.hasAnimIn();
      }
      public java.lang.String getAnimIn() {
        return result.getAnimIn();
      }
      public Builder setAnimIn(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasAnimIn = true;
        result.animIn_ = value;
        return this;
      }
      public Builder clearAnimIn() {
        result.hasAnimIn = false;
        result.animIn_ = getDefaultInstance().getAnimIn();
        return this;
      }
      
      // optional string enable_preload = 16;
      public boolean hasEnablePreload() {
        return result.hasEnablePreload();
      }
      public java.lang.String getEnablePreload() {
        return result.getEnablePreload();
      }
      public Builder setEnablePreload(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasEnablePreload = true;
        result.enablePreload_ = value;
        return this;
      }
      public Builder clearEnablePreload() {
        result.hasEnablePreload = false;
        result.enablePreload_ = getDefaultInstance().getEnablePreload();
        return this;
      }
      
      // optional string enable_page = 17;
      public boolean hasEnablePage() {
        return result.hasEnablePage();
      }
      public java.lang.String getEnablePage() {
        return result.getEnablePage();
      }
      public Builder setEnablePage(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasEnablePage = true;
        result.enablePage_ = value;
        return this;
      }
      public Builder clearEnablePage() {
        result.hasEnablePage = false;
        result.enablePage_ = getDefaultInstance().getEnablePage();
        return this;
      }
      
      // optional string status = 18;
      public boolean hasStatus() {
        return result.hasStatus();
      }
      public java.lang.String getStatus() {
        return result.getStatus();
      }
      public Builder setStatus(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasStatus = true;
        result.status_ = value;
        return this;
      }
      public Builder clearStatus() {
        result.hasStatus = false;
        result.status_ = getDefaultInstance().getStatus();
        return this;
      }
      
      // optional string ad_network_strategy = 19;
      public boolean hasAdNetworkStrategy() {
        return result.hasAdNetworkStrategy();
      }
      public java.lang.String getAdNetworkStrategy() {
        return result.getAdNetworkStrategy();
      }
      public Builder setAdNetworkStrategy(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasAdNetworkStrategy = true;
        result.adNetworkStrategy_ = value;
        return this;
      }
      public Builder clearAdNetworkStrategy() {
        result.hasAdNetworkStrategy = false;
        result.adNetworkStrategy_ = getDefaultInstance().getAdNetworkStrategy();
        return this;
      }
      
      // optional bool xp_enable = 20;
      public boolean hasXpEnable() {
        return result.hasXpEnable();
      }
      public boolean getXpEnable() {
        return result.getXpEnable();
      }
      public Builder setXpEnable(boolean value) {
        result.hasXpEnable = true;
        result.xpEnable_ = value;
        return this;
      }
      public Builder clearXpEnable() {
        result.hasXpEnable = false;
        result.xpEnable_ = false;
        return this;
      }
      
      // optional int32 xp_percent = 21;
      public boolean hasXpPercent() {
        return result.hasXpPercent();
      }
      public int getXpPercent() {
        return result.getXpPercent();
      }
      public Builder setXpPercent(int value) {
        result.hasXpPercent = true;
        result.xpPercent_ = value;
        return this;
      }
      public Builder clearXpPercent() {
        result.hasXpPercent = false;
        result.xpPercent_ = 0;
        return this;
      }
      
      // optional string appkey = 22;
      public boolean hasAppkey() {
        return result.hasAppkey();
      }
      public java.lang.String getAppkey() {
        return result.getAppkey();
      }
      public Builder setAppkey(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasAppkey = true;
        result.appkey_ = value;
        return this;
      }
      public Builder clearAppkey() {
        result.hasAppkey = false;
        result.appkey_ = getDefaultInstance().getAppkey();
        return this;
      }
      
      // optional bool uads_enable = 23;
      public boolean hasUadsEnable() {
        return result.hasUadsEnable();
      }
      public boolean getUadsEnable() {
        return result.getUadsEnable();
      }
      public Builder setUadsEnable(boolean value) {
        result.hasUadsEnable = true;
        result.uadsEnable_ = value;
        return this;
      }
      public Builder clearUadsEnable() {
        result.hasUadsEnable = false;
        result.uadsEnable_ = false;
        return this;
      }
      
      // optional int32 uads_percent = 24;
      public boolean hasUadsPercent() {
        return result.hasUadsPercent();
      }
      public int getUadsPercent() {
        return result.getUadsPercent();
      }
      public Builder setUadsPercent(int value) {
        result.hasUadsPercent = true;
        result.uadsPercent_ = value;
        return this;
      }
      public Builder clearUadsPercent() {
        result.hasUadsPercent = false;
        result.uadsPercent_ = 0;
        return this;
      }
      
      // optional string uads_key = 25;
      public boolean hasUadsKey() {
        return result.hasUadsKey();
      }
      public java.lang.String getUadsKey() {
        return result.getUadsKey();
      }
      public Builder setUadsKey(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasUadsKey = true;
        result.uadsKey_ = value;
        return this;
      }
      public Builder clearUadsKey() {
        result.hasUadsKey = false;
        result.uadsKey_ = getDefaultInstance().getUadsKey();
        return this;
      }
      
      // optional string uads_key2 = 26;
      public boolean hasUadsKey2() {
        return result.hasUadsKey2();
      }
      public java.lang.String getUadsKey2() {
        return result.getUadsKey2();
      }
      public Builder setUadsKey2(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasUadsKey2 = true;
        result.uadsKey2_ = value;
        return this;
      }
      public Builder clearUadsKey2() {
        result.hasUadsKey2 = false;
        result.uadsKey2_ = getDefaultInstance().getUadsKey2();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:com.umeng.ufp.core.domain.protobuf.AdSlotEntry)
    }
    
    static {
      defaultInstance = new AdSlotEntry(true);
      com.umeng.ufp.core.domain.protobuf.AdSlotProtos.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.umeng.ufp.core.domain.protobuf.AdSlotEntry)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_umeng_ufp_core_domain_protobuf_AdSlotEntry_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_umeng_ufp_core_domain_protobuf_AdSlotEntry_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023ad_slot_entry.proto\022\"com.umeng.ufp.cor" +
      "e.domain.protobuf\"\202\004\n\013AdSlotEntry\022\n\n\002id\030" +
      "\001 \001(\005\022\016\n\006app_id\030\002 \001(\005\022\014\n\004name\030\003 \001(\t\022\024\n\014l" +
      "anding_type\030\004 \001(\t\022\024\n\014landing_size\030\005 \001(\t\022" +
      "\026\n\016landing_images\030\006 \001(\t\022\020\n\010platform\030\007 \001(" +
      "\t\022\016\n\006device\030\010 \001(\t\022\020\n\010channels\030\t \001(\t\022\r\n\005a" +
      "reas\030\n \001(\t\022\021\n\ttext_size\030\013 \001(\t\022\030\n\020display" +
      "_strategy\030\014 \001(\t\022\021\n\ttimeslots\030\r \001(\t\022\020\n\010te" +
      "mplate\030\016 \001(\t\022\017\n\007anim_in\030\017 \001(\t\022\026\n\016enable_" +
      "preload\030\020 \001(\t\022\023\n\013enable_page\030\021 \001(\t\022\016\n\006st",
      "atus\030\022 \001(\t\022\033\n\023ad_network_strategy\030\023 \001(\t\022" +
      "\021\n\txp_enable\030\024 \001(\010\022\022\n\nxp_percent\030\025 \001(\005\022\016" +
      "\n\006appkey\030\026 \001(\t\022\023\n\013uads_enable\030\027 \001(\010\022\024\n\014u" +
      "ads_percent\030\030 \001(\005\022\020\n\010uads_key\030\031 \001(\t\022\021\n\tu" +
      "ads_key2\030\032 \001(\tB2\n\"com.umeng.ufp.core.dom" +
      "ain.protobufB\014AdSlotProtos"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_umeng_ufp_core_domain_protobuf_AdSlotEntry_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_umeng_ufp_core_domain_protobuf_AdSlotEntry_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_umeng_ufp_core_domain_protobuf_AdSlotEntry_descriptor,
              new java.lang.String[] { "Id", "AppId", "Name", "LandingType", "LandingSize", "LandingImages", "Platform", "Device", "Channels", "Areas", "TextSize", "DisplayStrategy", "Timeslots", "Template", "AnimIn", "EnablePreload", "EnablePage", "Status", "AdNetworkStrategy", "XpEnable", "XpPercent", "Appkey", "UadsEnable", "UadsPercent", "UadsKey", "UadsKey2", },
              com.umeng.ufp.core.domain.protobuf.AdSlotProtos.AdSlotEntry.class,
              com.umeng.ufp.core.domain.protobuf.AdSlotProtos.AdSlotEntry.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  public static void internalForceInit() {}
  
  // @@protoc_insertion_point(outer_class_scope)
}
