// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user_action_log_entry.proto

package com.umeng.ufp.core.domain.protobuf;

public final class UserActionLogProtos {
  private UserActionLogProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public static final class UserActionLogEntry extends
      com.google.protobuf.GeneratedMessage {
    // Use UserActionLogEntry.newBuilder() to construct.
    private UserActionLogEntry() {
      initFields();
    }
    private UserActionLogEntry(boolean noInit) {}
    
    private static final UserActionLogEntry defaultInstance;
    public static UserActionLogEntry getDefaultInstance() {
      return defaultInstance;
    }
    
    public UserActionLogEntry getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.umeng.ufp.core.domain.protobuf.UserActionLogProtos.internal_static_com_umeng_ufp_core_domain_protobuf_UserActionLogEntry_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.umeng.ufp.core.domain.protobuf.UserActionLogProtos.internal_static_com_umeng_ufp_core_domain_protobuf_UserActionLogEntry_fieldAccessorTable;
    }
    
    // optional string op_date = 1;
    public static final int OP_DATE_FIELD_NUMBER = 1;
    private boolean hasOpDate;
    private java.lang.String opDate_ = "";
    public boolean hasOpDate() { return hasOpDate; }
    public java.lang.String getOpDate() { return opDate_; }
    
    // optional string op_type = 2;
    public static final int OP_TYPE_FIELD_NUMBER = 2;
    private boolean hasOpType;
    private java.lang.String opType_ = "";
    public boolean hasOpType() { return hasOpType; }
    public java.lang.String getOpType() { return opType_; }
    
    // optional string object_type = 3;
    public static final int OBJECT_TYPE_FIELD_NUMBER = 3;
    private boolean hasObjectType;
    private java.lang.String objectType_ = "";
    public boolean hasObjectType() { return hasObjectType; }
    public java.lang.String getObjectType() { return objectType_; }
    
    // optional int32 object_id = 4;
    public static final int OBJECT_ID_FIELD_NUMBER = 4;
    private boolean hasObjectId;
    private int objectId_ = 0;
    public boolean hasObjectId() { return hasObjectId; }
    public int getObjectId() { return objectId_; }
    
    // optional bytes object_oldvalue = 5;
    public static final int OBJECT_OLDVALUE_FIELD_NUMBER = 5;
    private boolean hasObjectOldvalue;
    private com.google.protobuf.ByteString objectOldvalue_ = com.google.protobuf.ByteString.EMPTY;
    public boolean hasObjectOldvalue() { return hasObjectOldvalue; }
    public com.google.protobuf.ByteString getObjectOldvalue() { return objectOldvalue_; }
    
    // optional bytes object_newvalue = 6;
    public static final int OBJECT_NEWVALUE_FIELD_NUMBER = 6;
    private boolean hasObjectNewvalue;
    private com.google.protobuf.ByteString objectNewvalue_ = com.google.protobuf.ByteString.EMPTY;
    public boolean hasObjectNewvalue() { return hasObjectNewvalue; }
    public com.google.protobuf.ByteString getObjectNewvalue() { return objectNewvalue_; }
    
    // optional int32 user_id = 7;
    public static final int USER_ID_FIELD_NUMBER = 7;
    private boolean hasUserId;
    private int userId_ = 0;
    public boolean hasUserId() { return hasUserId; }
    public int getUserId() { return userId_; }
    
    // optional int32 operator_id = 8;
    public static final int OPERATOR_ID_FIELD_NUMBER = 8;
    private boolean hasOperatorId;
    private int operatorId_ = 0;
    public boolean hasOperatorId() { return hasOperatorId; }
    public int getOperatorId() { return operatorId_; }
    
    private void initFields() {
    }
    public final boolean isInitialized() {
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasOpDate()) {
        output.writeString(1, getOpDate());
      }
      if (hasOpType()) {
        output.writeString(2, getOpType());
      }
      if (hasObjectType()) {
        output.writeString(3, getObjectType());
      }
      if (hasObjectId()) {
        output.writeInt32(4, getObjectId());
      }
      if (hasObjectOldvalue()) {
        output.writeBytes(5, getObjectOldvalue());
      }
      if (hasObjectNewvalue()) {
        output.writeBytes(6, getObjectNewvalue());
      }
      if (hasUserId()) {
        output.writeInt32(7, getUserId());
      }
      if (hasOperatorId()) {
        output.writeInt32(8, getOperatorId());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasOpDate()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(1, getOpDate());
      }
      if (hasOpType()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(2, getOpType());
      }
      if (hasObjectType()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(3, getObjectType());
      }
      if (hasObjectId()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, getObjectId());
      }
      if (hasObjectOldvalue()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, getObjectOldvalue());
      }
      if (hasObjectNewvalue()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(6, getObjectNewvalue());
      }
      if (hasUserId()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(7, getUserId());
      }
      if (hasOperatorId()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(8, getOperatorId());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static com.umeng.ufp.core.domain.protobuf.UserActionLogProtos.UserActionLogEntry parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.umeng.ufp.core.domain.protobuf.UserActionLogProtos.UserActionLogEntry parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.umeng.ufp.core.domain.protobuf.UserActionLogProtos.UserActionLogEntry parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.umeng.ufp.core.domain.protobuf.UserActionLogProtos.UserActionLogEntry parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.umeng.ufp.core.domain.protobuf.UserActionLogProtos.UserActionLogEntry parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.umeng.ufp.core.domain.protobuf.UserActionLogProtos.UserActionLogEntry parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.umeng.ufp.core.domain.protobuf.UserActionLogProtos.UserActionLogEntry parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.umeng.ufp.core.domain.protobuf.UserActionLogProtos.UserActionLogEntry parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.umeng.ufp.core.domain.protobuf.UserActionLogProtos.UserActionLogEntry parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.umeng.ufp.core.domain.protobuf.UserActionLogProtos.UserActionLogEntry parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.umeng.ufp.core.domain.protobuf.UserActionLogProtos.UserActionLogEntry prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private com.umeng.ufp.core.domain.protobuf.UserActionLogProtos.UserActionLogEntry result;
      
      // Construct using com.umeng.ufp.core.domain.protobuf.UserActionLogProtos.UserActionLogEntry.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new com.umeng.ufp.core.domain.protobuf.UserActionLogProtos.UserActionLogEntry();
        return builder;
      }
      
      protected com.umeng.ufp.core.domain.protobuf.UserActionLogProtos.UserActionLogEntry internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new com.umeng.ufp.core.domain.protobuf.UserActionLogProtos.UserActionLogEntry();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.umeng.ufp.core.domain.protobuf.UserActionLogProtos.UserActionLogEntry.getDescriptor();
      }
      
      public com.umeng.ufp.core.domain.protobuf.UserActionLogProtos.UserActionLogEntry getDefaultInstanceForType() {
        return com.umeng.ufp.core.domain.protobuf.UserActionLogProtos.UserActionLogEntry.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public com.umeng.ufp.core.domain.protobuf.UserActionLogProtos.UserActionLogEntry build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private com.umeng.ufp.core.domain.protobuf.UserActionLogProtos.UserActionLogEntry buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.umeng.ufp.core.domain.protobuf.UserActionLogProtos.UserActionLogEntry buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        com.umeng.ufp.core.domain.protobuf.UserActionLogProtos.UserActionLogEntry returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.umeng.ufp.core.domain.protobuf.UserActionLogProtos.UserActionLogEntry) {
          return mergeFrom((com.umeng.ufp.core.domain.protobuf.UserActionLogProtos.UserActionLogEntry)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.umeng.ufp.core.domain.protobuf.UserActionLogProtos.UserActionLogEntry other) {
        if (other == com.umeng.ufp.core.domain.protobuf.UserActionLogProtos.UserActionLogEntry.getDefaultInstance()) return this;
        if (other.hasOpDate()) {
          setOpDate(other.getOpDate());
        }
        if (other.hasOpType()) {
          setOpType(other.getOpType());
        }
        if (other.hasObjectType()) {
          setObjectType(other.getObjectType());
        }
        if (other.hasObjectId()) {
          setObjectId(other.getObjectId());
        }
        if (other.hasObjectOldvalue()) {
          setObjectOldvalue(other.getObjectOldvalue());
        }
        if (other.hasObjectNewvalue()) {
          setObjectNewvalue(other.getObjectNewvalue());
        }
        if (other.hasUserId()) {
          setUserId(other.getUserId());
        }
        if (other.hasOperatorId()) {
          setOperatorId(other.getOperatorId());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 10: {
              setOpDate(input.readString());
              break;
            }
            case 18: {
              setOpType(input.readString());
              break;
            }
            case 26: {
              setObjectType(input.readString());
              break;
            }
            case 32: {
              setObjectId(input.readInt32());
              break;
            }
            case 42: {
              setObjectOldvalue(input.readBytes());
              break;
            }
            case 50: {
              setObjectNewvalue(input.readBytes());
              break;
            }
            case 56: {
              setUserId(input.readInt32());
              break;
            }
            case 64: {
              setOperatorId(input.readInt32());
              break;
            }
          }
        }
      }
      
      
      // optional string op_date = 1;
      public boolean hasOpDate() {
        return result.hasOpDate();
      }
      public java.lang.String getOpDate() {
        return result.getOpDate();
      }
      public Builder setOpDate(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasOpDate = true;
        result.opDate_ = value;
        return this;
      }
      public Builder clearOpDate() {
        result.hasOpDate = false;
        result.opDate_ = getDefaultInstance().getOpDate();
        return this;
      }
      
      // optional string op_type = 2;
      public boolean hasOpType() {
        return result.hasOpType();
      }
      public java.lang.String getOpType() {
        return result.getOpType();
      }
      public Builder setOpType(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasOpType = true;
        result.opType_ = value;
        return this;
      }
      public Builder clearOpType() {
        result.hasOpType = false;
        result.opType_ = getDefaultInstance().getOpType();
        return this;
      }
      
      // optional string object_type = 3;
      public boolean hasObjectType() {
        return result.hasObjectType();
      }
      public java.lang.String getObjectType() {
        return result.getObjectType();
      }
      public Builder setObjectType(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasObjectType = true;
        result.objectType_ = value;
        return this;
      }
      public Builder clearObjectType() {
        result.hasObjectType = false;
        result.objectType_ = getDefaultInstance().getObjectType();
        return this;
      }
      
      // optional int32 object_id = 4;
      public boolean hasObjectId() {
        return result.hasObjectId();
      }
      public int getObjectId() {
        return result.getObjectId();
      }
      public Builder setObjectId(int value) {
        result.hasObjectId = true;
        result.objectId_ = value;
        return this;
      }
      public Builder clearObjectId() {
        result.hasObjectId = false;
        result.objectId_ = 0;
        return this;
      }
      
      // optional bytes object_oldvalue = 5;
      public boolean hasObjectOldvalue() {
        return result.hasObjectOldvalue();
      }
      public com.google.protobuf.ByteString getObjectOldvalue() {
        return result.getObjectOldvalue();
      }
      public Builder setObjectOldvalue(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasObjectOldvalue = true;
        result.objectOldvalue_ = value;
        return this;
      }
      public Builder clearObjectOldvalue() {
        result.hasObjectOldvalue = false;
        result.objectOldvalue_ = getDefaultInstance().getObjectOldvalue();
        return this;
      }
      
      // optional bytes object_newvalue = 6;
      public boolean hasObjectNewvalue() {
        return result.hasObjectNewvalue();
      }
      public com.google.protobuf.ByteString getObjectNewvalue() {
        return result.getObjectNewvalue();
      }
      public Builder setObjectNewvalue(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasObjectNewvalue = true;
        result.objectNewvalue_ = value;
        return this;
      }
      public Builder clearObjectNewvalue() {
        result.hasObjectNewvalue = false;
        result.objectNewvalue_ = getDefaultInstance().getObjectNewvalue();
        return this;
      }
      
      // optional int32 user_id = 7;
      public boolean hasUserId() {
        return result.hasUserId();
      }
      public int getUserId() {
        return result.getUserId();
      }
      public Builder setUserId(int value) {
        result.hasUserId = true;
        result.userId_ = value;
        return this;
      }
      public Builder clearUserId() {
        result.hasUserId = false;
        result.userId_ = 0;
        return this;
      }
      
      // optional int32 operator_id = 8;
      public boolean hasOperatorId() {
        return result.hasOperatorId();
      }
      public int getOperatorId() {
        return result.getOperatorId();
      }
      public Builder setOperatorId(int value) {
        result.hasOperatorId = true;
        result.operatorId_ = value;
        return this;
      }
      public Builder clearOperatorId() {
        result.hasOperatorId = false;
        result.operatorId_ = 0;
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:com.umeng.ufp.core.domain.protobuf.UserActionLogEntry)
    }
    
    static {
      defaultInstance = new UserActionLogEntry(true);
      com.umeng.ufp.core.domain.protobuf.UserActionLogProtos.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.umeng.ufp.core.domain.protobuf.UserActionLogEntry)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_umeng_ufp_core_domain_protobuf_UserActionLogEntry_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_umeng_ufp_core_domain_protobuf_UserActionLogEntry_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\033user_action_log_entry.proto\022\"com.umeng" +
      ".ufp.core.domain.protobuf\"\266\001\n\022UserAction" +
      "LogEntry\022\017\n\007op_date\030\001 \001(\t\022\017\n\007op_type\030\002 \001" +
      "(\t\022\023\n\013object_type\030\003 \001(\t\022\021\n\tobject_id\030\004 \001" +
      "(\005\022\027\n\017object_oldvalue\030\005 \001(\014\022\027\n\017object_ne" +
      "wvalue\030\006 \001(\014\022\017\n\007user_id\030\007 \001(\005\022\023\n\013operato" +
      "r_id\030\010 \001(\005B9\n\"com.umeng.ufp.core.domain." +
      "protobufB\023UserActionLogProtos"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_umeng_ufp_core_domain_protobuf_UserActionLogEntry_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_umeng_ufp_core_domain_protobuf_UserActionLogEntry_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_umeng_ufp_core_domain_protobuf_UserActionLogEntry_descriptor,
              new java.lang.String[] { "OpDate", "OpType", "ObjectType", "ObjectId", "ObjectOldvalue", "ObjectNewvalue", "UserId", "OperatorId", },
              com.umeng.ufp.core.domain.protobuf.UserActionLogProtos.UserActionLogEntry.class,
              com.umeng.ufp.core.domain.protobuf.UserActionLogProtos.UserActionLogEntry.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  public static void internalForceInit() {}
  
  // @@protoc_insertion_point(outer_class_scope)
}
