// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user_entry.proto

package com.umeng.ufp.core.domain.protobuf;

public final class UserProtos {
  private UserProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public static final class UserEntry extends
      com.google.protobuf.GeneratedMessage {
    // Use UserEntry.newBuilder() to construct.
    private UserEntry() {
      initFields();
    }
    private UserEntry(boolean noInit) {}
    
    private static final UserEntry defaultInstance;
    public static UserEntry getDefaultInstance() {
      return defaultInstance;
    }
    
    public UserEntry getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.umeng.ufp.core.domain.protobuf.UserProtos.internal_static_com_umeng_ufp_core_domain_protobuf_UserEntry_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.umeng.ufp.core.domain.protobuf.UserProtos.internal_static_com_umeng_ufp_core_domain_protobuf_UserEntry_fieldAccessorTable;
    }
    
    // optional int32 id = 1;
    public static final int ID_FIELD_NUMBER = 1;
    private boolean hasId;
    private int id_ = 0;
    public boolean hasId() { return hasId; }
    public int getId() { return id_; }
    
    // optional string email = 2;
    public static final int EMAIL_FIELD_NUMBER = 2;
    private boolean hasEmail;
    private java.lang.String email_ = "";
    public boolean hasEmail() { return hasEmail; }
    public java.lang.String getEmail() { return email_; }
    
    // optional string nickname = 3;
    public static final int NICKNAME_FIELD_NUMBER = 3;
    private boolean hasNickname;
    private java.lang.String nickname_ = "";
    public boolean hasNickname() { return hasNickname; }
    public java.lang.String getNickname() { return nickname_; }
    
    // optional string password = 4;
    public static final int PASSWORD_FIELD_NUMBER = 4;
    private boolean hasPassword;
    private java.lang.String password_ = "";
    public boolean hasPassword() { return hasPassword; }
    public java.lang.String getPassword() { return password_; }
    
    // optional string type = 5;
    public static final int TYPE_FIELD_NUMBER = 5;
    private boolean hasType;
    private java.lang.String type_ = "";
    public boolean hasType() { return hasType; }
    public java.lang.String getType() { return type_; }
    
    // optional string name = 6;
    public static final int NAME_FIELD_NUMBER = 6;
    private boolean hasName;
    private java.lang.String name_ = "";
    public boolean hasName() { return hasName; }
    public java.lang.String getName() { return name_; }
    
    // optional string phone = 7;
    public static final int PHONE_FIELD_NUMBER = 7;
    private boolean hasPhone;
    private java.lang.String phone_ = "";
    public boolean hasPhone() { return hasPhone; }
    public java.lang.String getPhone() { return phone_; }
    
    // optional string logo_url = 8;
    public static final int LOGO_URL_FIELD_NUMBER = 8;
    private boolean hasLogoUrl;
    private java.lang.String logoUrl_ = "";
    public boolean hasLogoUrl() { return hasLogoUrl; }
    public java.lang.String getLogoUrl() { return logoUrl_; }
    
    // optional string logo_name = 9;
    public static final int LOGO_NAME_FIELD_NUMBER = 9;
    private boolean hasLogoName;
    private java.lang.String logoName_ = "";
    public boolean hasLogoName() { return hasLogoName; }
    public java.lang.String getLogoName() { return logoName_; }
    
    // optional string blacklist = 10;
    public static final int BLACKLIST_FIELD_NUMBER = 10;
    private boolean hasBlacklist;
    private java.lang.String blacklist_ = "";
    public boolean hasBlacklist() { return hasBlacklist; }
    public java.lang.String getBlacklist() { return blacklist_; }
    
    // optional string status = 11;
    public static final int STATUS_FIELD_NUMBER = 11;
    private boolean hasStatus;
    private java.lang.String status_ = "";
    public boolean hasStatus() { return hasStatus; }
    public java.lang.String getStatus() { return status_; }
    
    // optional int32 login_times = 12;
    public static final int LOGIN_TIMES_FIELD_NUMBER = 12;
    private boolean hasLoginTimes;
    private int loginTimes_ = 0;
    public boolean hasLoginTimes() { return hasLoginTimes; }
    public int getLoginTimes() { return loginTimes_; }
    
    // optional int64 last_login_time = 13;
    public static final int LAST_LOGIN_TIME_FIELD_NUMBER = 13;
    private boolean hasLastLoginTime;
    private long lastLoginTime_ = 0L;
    public boolean hasLastLoginTime() { return hasLastLoginTime; }
    public long getLastLoginTime() { return lastLoginTime_; }
    
    private void initFields() {
    }
    public final boolean isInitialized() {
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasId()) {
        output.writeInt32(1, getId());
      }
      if (hasEmail()) {
        output.writeString(2, getEmail());
      }
      if (hasNickname()) {
        output.writeString(3, getNickname());
      }
      if (hasPassword()) {
        output.writeString(4, getPassword());
      }
      if (hasType()) {
        output.writeString(5, getType());
      }
      if (hasName()) {
        output.writeString(6, getName());
      }
      if (hasPhone()) {
        output.writeString(7, getPhone());
      }
      if (hasLogoUrl()) {
        output.writeString(8, getLogoUrl());
      }
      if (hasLogoName()) {
        output.writeString(9, getLogoName());
      }
      if (hasBlacklist()) {
        output.writeString(10, getBlacklist());
      }
      if (hasStatus()) {
        output.writeString(11, getStatus());
      }
      if (hasLoginTimes()) {
        output.writeInt32(12, getLoginTimes());
      }
      if (hasLastLoginTime()) {
        output.writeInt64(13, getLastLoginTime());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasId()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, getId());
      }
      if (hasEmail()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(2, getEmail());
      }
      if (hasNickname()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(3, getNickname());
      }
      if (hasPassword()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(4, getPassword());
      }
      if (hasType()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(5, getType());
      }
      if (hasName()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(6, getName());
      }
      if (hasPhone()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(7, getPhone());
      }
      if (hasLogoUrl()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(8, getLogoUrl());
      }
      if (hasLogoName()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(9, getLogoName());
      }
      if (hasBlacklist()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(10, getBlacklist());
      }
      if (hasStatus()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(11, getStatus());
      }
      if (hasLoginTimes()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(12, getLoginTimes());
      }
      if (hasLastLoginTime()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(13, getLastLoginTime());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static com.umeng.ufp.core.domain.protobuf.UserProtos.UserEntry parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.umeng.ufp.core.domain.protobuf.UserProtos.UserEntry parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.umeng.ufp.core.domain.protobuf.UserProtos.UserEntry parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.umeng.ufp.core.domain.protobuf.UserProtos.UserEntry parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.umeng.ufp.core.domain.protobuf.UserProtos.UserEntry parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.umeng.ufp.core.domain.protobuf.UserProtos.UserEntry parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.umeng.ufp.core.domain.protobuf.UserProtos.UserEntry parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.umeng.ufp.core.domain.protobuf.UserProtos.UserEntry parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.umeng.ufp.core.domain.protobuf.UserProtos.UserEntry parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.umeng.ufp.core.domain.protobuf.UserProtos.UserEntry parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.umeng.ufp.core.domain.protobuf.UserProtos.UserEntry prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private com.umeng.ufp.core.domain.protobuf.UserProtos.UserEntry result;
      
      // Construct using com.umeng.ufp.core.domain.protobuf.UserProtos.UserEntry.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new com.umeng.ufp.core.domain.protobuf.UserProtos.UserEntry();
        return builder;
      }
      
      protected com.umeng.ufp.core.domain.protobuf.UserProtos.UserEntry internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new com.umeng.ufp.core.domain.protobuf.UserProtos.UserEntry();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.umeng.ufp.core.domain.protobuf.UserProtos.UserEntry.getDescriptor();
      }
      
      public com.umeng.ufp.core.domain.protobuf.UserProtos.UserEntry getDefaultInstanceForType() {
        return com.umeng.ufp.core.domain.protobuf.UserProtos.UserEntry.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public com.umeng.ufp.core.domain.protobuf.UserProtos.UserEntry build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private com.umeng.ufp.core.domain.protobuf.UserProtos.UserEntry buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.umeng.ufp.core.domain.protobuf.UserProtos.UserEntry buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        com.umeng.ufp.core.domain.protobuf.UserProtos.UserEntry returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.umeng.ufp.core.domain.protobuf.UserProtos.UserEntry) {
          return mergeFrom((com.umeng.ufp.core.domain.protobuf.UserProtos.UserEntry)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.umeng.ufp.core.domain.protobuf.UserProtos.UserEntry other) {
        if (other == com.umeng.ufp.core.domain.protobuf.UserProtos.UserEntry.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasEmail()) {
          setEmail(other.getEmail());
        }
        if (other.hasNickname()) {
          setNickname(other.getNickname());
        }
        if (other.hasPassword()) {
          setPassword(other.getPassword());
        }
        if (other.hasType()) {
          setType(other.getType());
        }
        if (other.hasName()) {
          setName(other.getName());
        }
        if (other.hasPhone()) {
          setPhone(other.getPhone());
        }
        if (other.hasLogoUrl()) {
          setLogoUrl(other.getLogoUrl());
        }
        if (other.hasLogoName()) {
          setLogoName(other.getLogoName());
        }
        if (other.hasBlacklist()) {
          setBlacklist(other.getBlacklist());
        }
        if (other.hasStatus()) {
          setStatus(other.getStatus());
        }
        if (other.hasLoginTimes()) {
          setLoginTimes(other.getLoginTimes());
        }
        if (other.hasLastLoginTime()) {
          setLastLoginTime(other.getLastLoginTime());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 8: {
              setId(input.readInt32());
              break;
            }
            case 18: {
              setEmail(input.readString());
              break;
            }
            case 26: {
              setNickname(input.readString());
              break;
            }
            case 34: {
              setPassword(input.readString());
              break;
            }
            case 42: {
              setType(input.readString());
              break;
            }
            case 50: {
              setName(input.readString());
              break;
            }
            case 58: {
              setPhone(input.readString());
              break;
            }
            case 66: {
              setLogoUrl(input.readString());
              break;
            }
            case 74: {
              setLogoName(input.readString());
              break;
            }
            case 82: {
              setBlacklist(input.readString());
              break;
            }
            case 90: {
              setStatus(input.readString());
              break;
            }
            case 96: {
              setLoginTimes(input.readInt32());
              break;
            }
            case 104: {
              setLastLoginTime(input.readInt64());
              break;
            }
          }
        }
      }
      
      
      // optional int32 id = 1;
      public boolean hasId() {
        return result.hasId();
      }
      public int getId() {
        return result.getId();
      }
      public Builder setId(int value) {
        result.hasId = true;
        result.id_ = value;
        return this;
      }
      public Builder clearId() {
        result.hasId = false;
        result.id_ = 0;
        return this;
      }
      
      // optional string email = 2;
      public boolean hasEmail() {
        return result.hasEmail();
      }
      public java.lang.String getEmail() {
        return result.getEmail();
      }
      public Builder setEmail(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasEmail = true;
        result.email_ = value;
        return this;
      }
      public Builder clearEmail() {
        result.hasEmail = false;
        result.email_ = getDefaultInstance().getEmail();
        return this;
      }
      
      // optional string nickname = 3;
      public boolean hasNickname() {
        return result.hasNickname();
      }
      public java.lang.String getNickname() {
        return result.getNickname();
      }
      public Builder setNickname(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasNickname = true;
        result.nickname_ = value;
        return this;
      }
      public Builder clearNickname() {
        result.hasNickname = false;
        result.nickname_ = getDefaultInstance().getNickname();
        return this;
      }
      
      // optional string password = 4;
      public boolean hasPassword() {
        return result.hasPassword();
      }
      public java.lang.String getPassword() {
        return result.getPassword();
      }
      public Builder setPassword(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasPassword = true;
        result.password_ = value;
        return this;
      }
      public Builder clearPassword() {
        result.hasPassword = false;
        result.password_ = getDefaultInstance().getPassword();
        return this;
      }
      
      // optional string type = 5;
      public boolean hasType() {
        return result.hasType();
      }
      public java.lang.String getType() {
        return result.getType();
      }
      public Builder setType(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasType = true;
        result.type_ = value;
        return this;
      }
      public Builder clearType() {
        result.hasType = false;
        result.type_ = getDefaultInstance().getType();
        return this;
      }
      
      // optional string name = 6;
      public boolean hasName() {
        return result.hasName();
      }
      public java.lang.String getName() {
        return result.getName();
      }
      public Builder setName(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasName = true;
        result.name_ = value;
        return this;
      }
      public Builder clearName() {
        result.hasName = false;
        result.name_ = getDefaultInstance().getName();
        return this;
      }
      
      // optional string phone = 7;
      public boolean hasPhone() {
        return result.hasPhone();
      }
      public java.lang.String getPhone() {
        return result.getPhone();
      }
      public Builder setPhone(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasPhone = true;
        result.phone_ = value;
        return this;
      }
      public Builder clearPhone() {
        result.hasPhone = false;
        result.phone_ = getDefaultInstance().getPhone();
        return this;
      }
      
      // optional string logo_url = 8;
      public boolean hasLogoUrl() {
        return result.hasLogoUrl();
      }
      public java.lang.String getLogoUrl() {
        return result.getLogoUrl();
      }
      public Builder setLogoUrl(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasLogoUrl = true;
        result.logoUrl_ = value;
        return this;
      }
      public Builder clearLogoUrl() {
        result.hasLogoUrl = false;
        result.logoUrl_ = getDefaultInstance().getLogoUrl();
        return this;
      }
      
      // optional string logo_name = 9;
      public boolean hasLogoName() {
        return result.hasLogoName();
      }
      public java.lang.String getLogoName() {
        return result.getLogoName();
      }
      public Builder setLogoName(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasLogoName = true;
        result.logoName_ = value;
        return this;
      }
      public Builder clearLogoName() {
        result.hasLogoName = false;
        result.logoName_ = getDefaultInstance().getLogoName();
        return this;
      }
      
      // optional string blacklist = 10;
      public boolean hasBlacklist() {
        return result.hasBlacklist();
      }
      public java.lang.String getBlacklist() {
        return result.getBlacklist();
      }
      public Builder setBlacklist(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasBlacklist = true;
        result.blacklist_ = value;
        return this;
      }
      public Builder clearBlacklist() {
        result.hasBlacklist = false;
        result.blacklist_ = getDefaultInstance().getBlacklist();
        return this;
      }
      
      // optional string status = 11;
      public boolean hasStatus() {
        return result.hasStatus();
      }
      public java.lang.String getStatus() {
        return result.getStatus();
      }
      public Builder setStatus(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasStatus = true;
        result.status_ = value;
        return this;
      }
      public Builder clearStatus() {
        result.hasStatus = false;
        result.status_ = getDefaultInstance().getStatus();
        return this;
      }
      
      // optional int32 login_times = 12;
      public boolean hasLoginTimes() {
        return result.hasLoginTimes();
      }
      public int getLoginTimes() {
        return result.getLoginTimes();
      }
      public Builder setLoginTimes(int value) {
        result.hasLoginTimes = true;
        result.loginTimes_ = value;
        return this;
      }
      public Builder clearLoginTimes() {
        result.hasLoginTimes = false;
        result.loginTimes_ = 0;
        return this;
      }
      
      // optional int64 last_login_time = 13;
      public boolean hasLastLoginTime() {
        return result.hasLastLoginTime();
      }
      public long getLastLoginTime() {
        return result.getLastLoginTime();
      }
      public Builder setLastLoginTime(long value) {
        result.hasLastLoginTime = true;
        result.lastLoginTime_ = value;
        return this;
      }
      public Builder clearLastLoginTime() {
        result.hasLastLoginTime = false;
        result.lastLoginTime_ = 0L;
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:com.umeng.ufp.core.domain.protobuf.UserEntry)
    }
    
    static {
      defaultInstance = new UserEntry(true);
      com.umeng.ufp.core.domain.protobuf.UserProtos.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.umeng.ufp.core.domain.protobuf.UserEntry)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_umeng_ufp_core_domain_protobuf_UserEntry_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_umeng_ufp_core_domain_protobuf_UserEntry_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020user_entry.proto\022\"com.umeng.ufp.core.d" +
      "omain.protobuf\"\353\001\n\tUserEntry\022\n\n\002id\030\001 \001(\005" +
      "\022\r\n\005email\030\002 \001(\t\022\020\n\010nickname\030\003 \001(\t\022\020\n\010pas" +
      "sword\030\004 \001(\t\022\014\n\004type\030\005 \001(\t\022\014\n\004name\030\006 \001(\t\022" +
      "\r\n\005phone\030\007 \001(\t\022\020\n\010logo_url\030\010 \001(\t\022\021\n\tlogo" +
      "_name\030\t \001(\t\022\021\n\tblacklist\030\n \001(\t\022\016\n\006status" +
      "\030\013 \001(\t\022\023\n\013login_times\030\014 \001(\005\022\027\n\017last_logi" +
      "n_time\030\r \001(\003B0\n\"com.umeng.ufp.core.domai" +
      "n.protobufB\nUserProtos"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_umeng_ufp_core_domain_protobuf_UserEntry_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_umeng_ufp_core_domain_protobuf_UserEntry_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_umeng_ufp_core_domain_protobuf_UserEntry_descriptor,
              new java.lang.String[] { "Id", "Email", "Nickname", "Password", "Type", "Name", "Phone", "LogoUrl", "LogoName", "Blacklist", "Status", "LoginTimes", "LastLoginTime", },
              com.umeng.ufp.core.domain.protobuf.UserProtos.UserEntry.class,
              com.umeng.ufp.core.domain.protobuf.UserProtos.UserEntry.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  public static void internalForceInit() {}
  
  // @@protoc_insertion_point(outer_class_scope)
}
