// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user_op_log_entry.proto

package com.umeng.ufp.core.domain.protobuf;

public final class UserOpLogProtos {
  private UserOpLogProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public static final class UserOpLogEntry extends
      com.google.protobuf.GeneratedMessage {
    // Use UserOpLogEntry.newBuilder() to construct.
    private UserOpLogEntry() {
      initFields();
    }
    private UserOpLogEntry(boolean noInit) {}
    
    private static final UserOpLogEntry defaultInstance;
    public static UserOpLogEntry getDefaultInstance() {
      return defaultInstance;
    }
    
    public UserOpLogEntry getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.umeng.ufp.core.domain.protobuf.UserOpLogProtos.internal_static_com_umeng_ufp_core_domain_protobuf_UserOpLogEntry_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.umeng.ufp.core.domain.protobuf.UserOpLogProtos.internal_static_com_umeng_ufp_core_domain_protobuf_UserOpLogEntry_fieldAccessorTable;
    }
    
    // optional string op_date = 1;
    public static final int OP_DATE_FIELD_NUMBER = 1;
    private boolean hasOpDate;
    private java.lang.String opDate_ = "";
    public boolean hasOpDate() { return hasOpDate; }
    public java.lang.String getOpDate() { return opDate_; }
    
    // optional string op_type = 2;
    public static final int OP_TYPE_FIELD_NUMBER = 2;
    private boolean hasOpType;
    private java.lang.String opType_ = "";
    public boolean hasOpType() { return hasOpType; }
    public java.lang.String getOpType() { return opType_; }
    
    // optional string object_type = 3;
    public static final int OBJECT_TYPE_FIELD_NUMBER = 3;
    private boolean hasObjectType;
    private java.lang.String objectType_ = "";
    public boolean hasObjectType() { return hasObjectType; }
    public java.lang.String getObjectType() { return objectType_; }
    
    // optional string object_key = 4;
    public static final int OBJECT_KEY_FIELD_NUMBER = 4;
    private boolean hasObjectKey;
    private java.lang.String objectKey_ = "";
    public boolean hasObjectKey() { return hasObjectKey; }
    public java.lang.String getObjectKey() { return objectKey_; }
    
    // optional string object_value = 5;
    public static final int OBJECT_VALUE_FIELD_NUMBER = 5;
    private boolean hasObjectValue;
    private java.lang.String objectValue_ = "";
    public boolean hasObjectValue() { return hasObjectValue; }
    public java.lang.String getObjectValue() { return objectValue_; }
    
    // optional int32 user_id = 6;
    public static final int USER_ID_FIELD_NUMBER = 6;
    private boolean hasUserId;
    private int userId_ = 0;
    public boolean hasUserId() { return hasUserId; }
    public int getUserId() { return userId_; }
    
    private void initFields() {
    }
    public final boolean isInitialized() {
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasOpDate()) {
        output.writeString(1, getOpDate());
      }
      if (hasOpType()) {
        output.writeString(2, getOpType());
      }
      if (hasObjectType()) {
        output.writeString(3, getObjectType());
      }
      if (hasObjectKey()) {
        output.writeString(4, getObjectKey());
      }
      if (hasObjectValue()) {
        output.writeString(5, getObjectValue());
      }
      if (hasUserId()) {
        output.writeInt32(6, getUserId());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasOpDate()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(1, getOpDate());
      }
      if (hasOpType()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(2, getOpType());
      }
      if (hasObjectType()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(3, getObjectType());
      }
      if (hasObjectKey()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(4, getObjectKey());
      }
      if (hasObjectValue()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(5, getObjectValue());
      }
      if (hasUserId()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(6, getUserId());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static com.umeng.ufp.core.domain.protobuf.UserOpLogProtos.UserOpLogEntry parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.umeng.ufp.core.domain.protobuf.UserOpLogProtos.UserOpLogEntry parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.umeng.ufp.core.domain.protobuf.UserOpLogProtos.UserOpLogEntry parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.umeng.ufp.core.domain.protobuf.UserOpLogProtos.UserOpLogEntry parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.umeng.ufp.core.domain.protobuf.UserOpLogProtos.UserOpLogEntry parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.umeng.ufp.core.domain.protobuf.UserOpLogProtos.UserOpLogEntry parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.umeng.ufp.core.domain.protobuf.UserOpLogProtos.UserOpLogEntry parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.umeng.ufp.core.domain.protobuf.UserOpLogProtos.UserOpLogEntry parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.umeng.ufp.core.domain.protobuf.UserOpLogProtos.UserOpLogEntry parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.umeng.ufp.core.domain.protobuf.UserOpLogProtos.UserOpLogEntry parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.umeng.ufp.core.domain.protobuf.UserOpLogProtos.UserOpLogEntry prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private com.umeng.ufp.core.domain.protobuf.UserOpLogProtos.UserOpLogEntry result;
      
      // Construct using com.umeng.ufp.core.domain.protobuf.UserOpLogProtos.UserOpLogEntry.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new com.umeng.ufp.core.domain.protobuf.UserOpLogProtos.UserOpLogEntry();
        return builder;
      }
      
      protected com.umeng.ufp.core.domain.protobuf.UserOpLogProtos.UserOpLogEntry internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new com.umeng.ufp.core.domain.protobuf.UserOpLogProtos.UserOpLogEntry();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.umeng.ufp.core.domain.protobuf.UserOpLogProtos.UserOpLogEntry.getDescriptor();
      }
      
      public com.umeng.ufp.core.domain.protobuf.UserOpLogProtos.UserOpLogEntry getDefaultInstanceForType() {
        return com.umeng.ufp.core.domain.protobuf.UserOpLogProtos.UserOpLogEntry.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public com.umeng.ufp.core.domain.protobuf.UserOpLogProtos.UserOpLogEntry build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private com.umeng.ufp.core.domain.protobuf.UserOpLogProtos.UserOpLogEntry buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.umeng.ufp.core.domain.protobuf.UserOpLogProtos.UserOpLogEntry buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        com.umeng.ufp.core.domain.protobuf.UserOpLogProtos.UserOpLogEntry returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.umeng.ufp.core.domain.protobuf.UserOpLogProtos.UserOpLogEntry) {
          return mergeFrom((com.umeng.ufp.core.domain.protobuf.UserOpLogProtos.UserOpLogEntry)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.umeng.ufp.core.domain.protobuf.UserOpLogProtos.UserOpLogEntry other) {
        if (other == com.umeng.ufp.core.domain.protobuf.UserOpLogProtos.UserOpLogEntry.getDefaultInstance()) return this;
        if (other.hasOpDate()) {
          setOpDate(other.getOpDate());
        }
        if (other.hasOpType()) {
          setOpType(other.getOpType());
        }
        if (other.hasObjectType()) {
          setObjectType(other.getObjectType());
        }
        if (other.hasObjectKey()) {
          setObjectKey(other.getObjectKey());
        }
        if (other.hasObjectValue()) {
          setObjectValue(other.getObjectValue());
        }
        if (other.hasUserId()) {
          setUserId(other.getUserId());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 10: {
              setOpDate(input.readString());
              break;
            }
            case 18: {
              setOpType(input.readString());
              break;
            }
            case 26: {
              setObjectType(input.readString());
              break;
            }
            case 34: {
              setObjectKey(input.readString());
              break;
            }
            case 42: {
              setObjectValue(input.readString());
              break;
            }
            case 48: {
              setUserId(input.readInt32());
              break;
            }
          }
        }
      }
      
      
      // optional string op_date = 1;
      public boolean hasOpDate() {
        return result.hasOpDate();
      }
      public java.lang.String getOpDate() {
        return result.getOpDate();
      }
      public Builder setOpDate(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasOpDate = true;
        result.opDate_ = value;
        return this;
      }
      public Builder clearOpDate() {
        result.hasOpDate = false;
        result.opDate_ = getDefaultInstance().getOpDate();
        return this;
      }
      
      // optional string op_type = 2;
      public boolean hasOpType() {
        return result.hasOpType();
      }
      public java.lang.String getOpType() {
        return result.getOpType();
      }
      public Builder setOpType(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasOpType = true;
        result.opType_ = value;
        return this;
      }
      public Builder clearOpType() {
        result.hasOpType = false;
        result.opType_ = getDefaultInstance().getOpType();
        return this;
      }
      
      // optional string object_type = 3;
      public boolean hasObjectType() {
        return result.hasObjectType();
      }
      public java.lang.String getObjectType() {
        return result.getObjectType();
      }
      public Builder setObjectType(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasObjectType = true;
        result.objectType_ = value;
        return this;
      }
      public Builder clearObjectType() {
        result.hasObjectType = false;
        result.objectType_ = getDefaultInstance().getObjectType();
        return this;
      }
      
      // optional string object_key = 4;
      public boolean hasObjectKey() {
        return result.hasObjectKey();
      }
      public java.lang.String getObjectKey() {
        return result.getObjectKey();
      }
      public Builder setObjectKey(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasObjectKey = true;
        result.objectKey_ = value;
        return this;
      }
      public Builder clearObjectKey() {
        result.hasObjectKey = false;
        result.objectKey_ = getDefaultInstance().getObjectKey();
        return this;
      }
      
      // optional string object_value = 5;
      public boolean hasObjectValue() {
        return result.hasObjectValue();
      }
      public java.lang.String getObjectValue() {
        return result.getObjectValue();
      }
      public Builder setObjectValue(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasObjectValue = true;
        result.objectValue_ = value;
        return this;
      }
      public Builder clearObjectValue() {
        result.hasObjectValue = false;
        result.objectValue_ = getDefaultInstance().getObjectValue();
        return this;
      }
      
      // optional int32 user_id = 6;
      public boolean hasUserId() {
        return result.hasUserId();
      }
      public int getUserId() {
        return result.getUserId();
      }
      public Builder setUserId(int value) {
        result.hasUserId = true;
        result.userId_ = value;
        return this;
      }
      public Builder clearUserId() {
        result.hasUserId = false;
        result.userId_ = 0;
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:com.umeng.ufp.core.domain.protobuf.UserOpLogEntry)
    }
    
    static {
      defaultInstance = new UserOpLogEntry(true);
      com.umeng.ufp.core.domain.protobuf.UserOpLogProtos.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.umeng.ufp.core.domain.protobuf.UserOpLogEntry)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_umeng_ufp_core_domain_protobuf_UserOpLogEntry_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_umeng_ufp_core_domain_protobuf_UserOpLogEntry_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\027user_op_log_entry.proto\022\"com.umeng.ufp" +
      ".core.domain.protobuf\"\202\001\n\016UserOpLogEntry" +
      "\022\017\n\007op_date\030\001 \001(\t\022\017\n\007op_type\030\002 \001(\t\022\023\n\013ob" +
      "ject_type\030\003 \001(\t\022\022\n\nobject_key\030\004 \001(\t\022\024\n\014o" +
      "bject_value\030\005 \001(\t\022\017\n\007user_id\030\006 \001(\005B5\n\"co" +
      "m.umeng.ufp.core.domain.protobufB\017UserOp" +
      "LogProtos"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_umeng_ufp_core_domain_protobuf_UserOpLogEntry_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_umeng_ufp_core_domain_protobuf_UserOpLogEntry_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_umeng_ufp_core_domain_protobuf_UserOpLogEntry_descriptor,
              new java.lang.String[] { "OpDate", "OpType", "ObjectType", "ObjectKey", "ObjectValue", "UserId", },
              com.umeng.ufp.core.domain.protobuf.UserOpLogProtos.UserOpLogEntry.class,
              com.umeng.ufp.core.domain.protobuf.UserOpLogProtos.UserOpLogEntry.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  public static void internalForceInit() {}
  
  // @@protoc_insertion_point(outer_class_scope)
}
